<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../FluxKnowledge.Domain/FluxKnowledge.Domain.csproj" />
    <ProjectReference Include="../FluxKnowledge.NativeWorker.Protocol/FluxKnowledge.NativeWorker.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>
</Project>
