<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/FluxKnowledge.Application/FluxKnowledge.Application.csproj" />
    <ProjectReference Include="../../src/FluxKnowledge.Infrastructure.Inference/FluxKnowledge.Infrastructure.Inference.csproj" />
    <ProjectReference Include="../../src/FluxKnowledge.Integrations/FluxKnowledge.Integrations.csproj" />
  </ItemGroup>
</Project>
