import json

from flux_llm_kb.code_index import parse_code_file


def test_parse_python_code_emits_semantic_chunks_symbols_and_references(tmp_path):
    root = tmp_path / "repo"
    src = root / "src"
    src.mkdir(parents=True)
    path = src / "orders.py"
    path.write_text(
        "\n".join(
            [
                "from fastapi import APIRouter",
                "",
                "router = APIRouter()",
                "",
                "class OrderService:",
                "    def build_invoice(self, order_id: str) -> str:",
                "        return f'invoice-{order_id}'",
                "",
                "@router.get('/orders/{order_id}')",
                "def get_order(order_id: str):",
                "    service = OrderService()",
                "    return service.build_invoice(order_id)",
            ]
        ),
        encoding="utf-8",
    )

    result = parse_code_file(path, root=root)

    assert result.metadata["language"] == "python"
    assert result.metadata["parser_status"] == "parsed"
    assert {chunk.title for chunk in result.chunks} == {
        "src/orders.py::module",
        "src/orders.py::OrderService",
        "src/orders.py::OrderService.build_invoice",
        "src/orders.py::get_order",
    }
    assert all(chunk.metadata["language"] == "python" for chunk in result.chunks)
    assert all(chunk.metadata["parser_status"] == "parsed" for chunk in result.chunks)
    assert any(
        symbol.qualified_name == "OrderService.build_invoice"
        and symbol.symbol_kind == "method"
        and symbol.line_start == 6
        for symbol in result.symbols
    )
    assert any(
        symbol.qualified_name == "get_order"
        and symbol.symbol_kind == "function"
        and symbol.metadata.get("routes") == ["/orders/{order_id}"]
        for symbol in result.symbols
    )
    assert any(reference.relationship_kind == "import" and reference.target == "fastapi.APIRouter" for reference in result.references)
    assert any(reference.relationship_kind == "call" and reference.target == "OrderService" for reference in result.references)


def test_parse_malformed_python_falls_back_to_redacted_text_chunk(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    path = root / "broken.py"
    path.write_text("def broken(:\n    return 'secret@example.com'\n", encoding="utf-8")

    result = parse_code_file(path, root=root)

    assert result.metadata["language"] == "python"
    assert result.metadata["parser_status"] == "fallback"
    assert result.metadata["parser_diagnostics"]["error_type"] == "SyntaxError"
    assert "secret@example.com" not in str(result.metadata)
    assert len(result.chunks) == 1
    assert result.chunks[0].title == "broken.py::fallback"
    assert result.chunks[0].metadata["parser_status"] == "fallback"
    assert "[REDACTED:email]" in result.chunks[0].body


def test_parse_sql_and_config_files_emit_code_metadata(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    sql = root / "0019_code_aware.sql"
    sql.write_text(
        "CREATE TABLE code_symbols (id uuid primary key);\nCREATE INDEX idx_code_symbols_name ON code_symbols (name);\n",
        encoding="utf-8",
    )
    config = root / "pyproject.toml"
    config.write_text("[project]\nname = 'demo'\n", encoding="utf-8")

    sql_result = parse_code_file(sql, root=root)
    config_result = parse_code_file(config, root=root)

    assert sql_result.metadata["language"] == "sql"
    assert any(symbol.symbol_kind == "table" and symbol.name == "code_symbols" for symbol in sql_result.symbols)
    assert any(symbol.symbol_kind == "index" and symbol.name == "idx_code_symbols_name" for symbol in sql_result.symbols)
    assert config_result.metadata["language"] == "toml"
    assert config_result.metadata["parser_status"] == "parsed"
    assert config_result.chunks[0].metadata["symbol_kind"] == "config"


def test_parse_generated_typescript_routes_and_notebook_cells(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    generated = root / "client.py"
    generated.write_text(
        "# Code generated by Flux benchmark. DO NOT EDIT.\n\nclass Client:\n    def fetch(self):\n        return {}\n",
        encoding="utf-8",
    )
    routes = root / "routes.ts"
    routes.write_text(
        "\n".join(
            [
                "import express from 'express';",
                "const router = express.Router();",
                "router.get('/api/orders/:orderId', async (req, res) => {",
                "  res.json({ id: req.params.orderId });",
                "});",
                "export function configureRoutes(app) {",
                "  app.use(router);",
                "}",
            ]
        ),
        encoding="utf-8",
    )
    notebook = root / "orders.ipynb"
    notebook.write_text(
        json.dumps(
            {
                "cells": [
                    {"cell_type": "markdown", "source": ["# Orders\n"]},
                    {"cell_type": "code", "source": ["print('orders')\n"]},
                ],
                "metadata": {},
                "nbformat": 4,
                "nbformat_minor": 5,
            }
        ),
        encoding="utf-8",
    )

    generated_result = parse_code_file(generated, root=root)
    routes_result = parse_code_file(routes, root=root)
    notebook_result = parse_code_file(notebook, root=root)

    assert generated_result.metadata["generated"] is True
    assert all(chunk.metadata["code"]["generated"] is True for chunk in generated_result.chunks)
    assert any(reference.relationship_kind == "route" and reference.target == "/api/orders/:orderId" for reference in routes_result.references)
    assert any(symbol.qualified_name == "configureRoutes" for symbol in routes_result.symbols)
    assert [chunk.metadata["cell_type"] for chunk in notebook_result.chunks] == ["markdown", "code"]
    assert all(symbol.symbol_kind == "notebook_cell" for symbol in notebook_result.symbols)
