import json

from flux_llm_kb.code_index import parse_code_file


def test_parse_code_file_decodes_utf16_bom_without_nul_chunks(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    path = root / "_references.js"
    path.write_bytes(
        "\n".join(
            [
                '/// <autosync enabled="true" />',
                '/// <reference path="modernizr-2.6.2.js" />',
                '/// <reference path="jquery-1.10.2.js" />',
            ]
        ).encode("utf-16")
    )

    result = parse_code_file(path, root=root)

    bodies = "\n".join(chunk.body for chunk in result.chunks)
    assert "\x00" not in bodies
    assert "jquery-1.10.2.js" in bodies


def test_parse_python_code_emits_semantic_chunks_symbols_and_references(tmp_path):
    root = tmp_path / "repo"
    src = root / "src"
    src.mkdir(parents=True)
    path = src / "orders.py"
    path.write_text(
        "\n".join(
            [
                "from fastapi import APIRouter",
                "",
                "router = APIRouter()",
                "",
                "class OrderService:",
                "    def build_invoice(self, order_id: str) -> str:",
                "        return f'invoice-{order_id}'",
                "",
                "@router.get('/orders/{order_id}')",
                "def get_order(order_id: str):",
                "    service = OrderService()",
                "    return service.build_invoice(order_id)",
            ]
        ),
        encoding="utf-8",
    )

    result = parse_code_file(path, root=root)

    assert result.metadata["language"] == "python"
    assert result.metadata["parser_status"] == "parsed"
    assert {chunk.title for chunk in result.chunks} == {
        "src/orders.py::module",
        "src/orders.py::OrderService",
        "src/orders.py::OrderService.build_invoice",
        "src/orders.py::get_order",
    }
    assert all(chunk.metadata["language"] == "python" for chunk in result.chunks)
    assert all(chunk.metadata["parser_status"] == "parsed" for chunk in result.chunks)
    assert any(
        symbol.qualified_name == "OrderService.build_invoice"
        and symbol.symbol_kind == "method"
        and symbol.line_start == 6
        for symbol in result.symbols
    )
    assert any(
        symbol.qualified_name == "get_order"
        and symbol.symbol_kind == "function"
        and symbol.metadata.get("routes") == ["/orders/{order_id}"]
        for symbol in result.symbols
    )
    assert any(reference.relationship_kind == "import" and reference.target == "fastapi.APIRouter" for reference in result.references)
    assert any(reference.relationship_kind == "call" and reference.target == "OrderService" for reference in result.references)


def test_parse_malformed_python_falls_back_to_redacted_text_chunk(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    path = root / "broken.py"
    path.write_text("def broken(:\n    return 'secret@example.com'\n", encoding="utf-8")

    result = parse_code_file(path, root=root)

    assert result.metadata["language"] == "python"
    assert result.metadata["parser_status"] == "fallback"
    assert result.metadata["parser_diagnostics"]["error_type"] == "SyntaxError"
    assert "secret@example.com" not in str(result.metadata)
    assert len(result.chunks) == 1
    assert result.chunks[0].title == "broken.py::fallback"
    assert result.chunks[0].metadata["parser_status"] == "fallback"
    assert "[REDACTED:email]" in result.chunks[0].body


def test_parse_sql_and_config_files_emit_code_metadata(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    sql = root / "0019_code_aware.sql"
    sql.write_text(
        "CREATE TABLE code_symbols (id uuid primary key);\nCREATE INDEX idx_code_symbols_name ON code_symbols (name);\n",
        encoding="utf-8",
    )
    config = root / "pyproject.toml"
    config.write_text("[project]\nname = 'demo'\n", encoding="utf-8")

    sql_result = parse_code_file(sql, root=root)
    config_result = parse_code_file(config, root=root)

    assert sql_result.metadata["language"] == "sql"
    assert any(symbol.symbol_kind == "table" and symbol.name == "code_symbols" for symbol in sql_result.symbols)
    assert any(symbol.symbol_kind == "index" and symbol.name == "idx_code_symbols_name" for symbol in sql_result.symbols)
    assert config_result.metadata["language"] == "toml"
    assert config_result.metadata["parser_status"] == "parsed"
    assert config_result.chunks[0].metadata["symbol_kind"] == "config"


def test_parse_generated_typescript_routes_and_notebook_cells(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    generated = root / "client.py"
    generated.write_text(
        "# Code generated by Flux benchmark. DO NOT EDIT.\n\nclass Client:\n    def fetch(self):\n        return {}\n",
        encoding="utf-8",
    )
    routes = root / "routes.ts"
    routes.write_text(
        "\n".join(
            [
                "import express from 'express';",
                "const router = express.Router();",
                "router.get('/api/orders/:orderId', async (req, res) => {",
                "  res.json({ id: req.params.orderId });",
                "});",
                "export function configureRoutes(app) {",
                "  app.use(router);",
                "}",
            ]
        ),
        encoding="utf-8",
    )
    notebook = root / "orders.ipynb"
    notebook.write_text(
        json.dumps(
            {
                "cells": [
                    {"cell_type": "markdown", "source": ["# Orders\n"]},
                    {"cell_type": "code", "source": ["print('orders')\n"]},
                ],
                "metadata": {},
                "nbformat": 4,
                "nbformat_minor": 5,
            }
        ),
        encoding="utf-8",
    )

    generated_result = parse_code_file(generated, root=root)
    routes_result = parse_code_file(routes, root=root)
    notebook_result = parse_code_file(notebook, root=root)

    assert generated_result.metadata["generated"] is True
    assert all(chunk.metadata["code"]["generated"] is True for chunk in generated_result.chunks)
    assert any(reference.relationship_kind == "route" and reference.target == "/api/orders/:orderId" for reference in routes_result.references)
    assert any(symbol.qualified_name == "configureRoutes" for symbol in routes_result.symbols)
    assert [chunk.metadata["cell_type"] for chunk in notebook_result.chunks] == ["markdown", "code"]
    assert all(symbol.symbol_kind == "notebook_cell" for symbol in notebook_result.symbols)


def test_parse_python_tests_emits_test_and_fixture_relationships(tmp_path):
    root = tmp_path / "repo"
    tests = root / "tests"
    tests.mkdir(parents=True)
    path = tests / "test_orders.py"
    path.write_text(
        "\n".join(
            [
                "import pytest",
                "from src.orders import OrderService",
                "",
                "@pytest.fixture",
                "def order_service():",
                "    return OrderService()",
                "",
                "def test_build_invoice(order_service):",
                "    assert order_service.build_invoice('order-1')",
            ]
        ),
        encoding="utf-8",
    )

    result = parse_code_file(path, root=root)

    assert any(symbol.qualified_name == "order_service" and symbol.symbol_kind == "fixture" for symbol in result.symbols)
    assert any(symbol.qualified_name == "test_build_invoice" and symbol.symbol_kind == "test" for symbol in result.symbols)
    assert any(
        reference.relationship_kind == "fixture"
        and reference.target == "order_service"
        and reference.source_symbol == "test_build_invoice"
        for reference in result.references
    )
    assert any(
        reference.relationship_kind == "test"
        and reference.target == "order_service.build_invoice"
        and reference.source_symbol == "test_build_invoice"
        for reference in result.references
    )


def test_parse_python_classes_emit_decorator_and_inheritance_relationships(tmp_path):
    root = tmp_path / "repo"
    src = root / "src"
    src.mkdir(parents=True)
    path = src / "models.py"
    path.write_text(
        "\n".join(
            [
                "from dataclasses import dataclass",
                "from pydantic import BaseModel",
                "",
                "class OrderDto(BaseModel):",
                "    id: str",
                "",
                "@dataclass(slots=True)",
                "class OrderRecord:",
                "    id: str",
                "",
                "class SpecialOrder(OrderRecord):",
                "    pass",
            ]
        ),
        encoding="utf-8",
    )

    result = parse_code_file(path, root=root)

    assert any(
        symbol.qualified_name == "OrderDto"
        and symbol.metadata.get("bases") == ["BaseModel"]
        for symbol in result.symbols
    )
    assert any(
        symbol.qualified_name == "OrderRecord"
        and symbol.metadata.get("decorators") == ["dataclass"]
        for symbol in result.symbols
    )
    assert any(reference.relationship_kind == "inherits" and reference.target == "BaseModel" for reference in result.references)
    assert any(reference.relationship_kind == "inherits" and reference.target == "OrderRecord" for reference in result.references)
    assert any(reference.relationship_kind == "decorator" and reference.target == "dataclass" for reference in result.references)


def test_parse_javascript_exports_callers_and_route_handlers(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    path = root / "routes.ts"
    path.write_text(
        "\n".join(
            [
                "import express from 'express';",
                "const router = express.Router();",
                "function renderOrder(id) { return { id }; }",
                "export const buildOrder = (req) => renderOrder(req.params.orderId);",
                "router.post('/api/orders/:orderId', buildOrder);",
                "export default class OrdersController {}",
            ]
        ),
        encoding="utf-8",
    )

    result = parse_code_file(path, root=root)

    assert any(symbol.qualified_name == "buildOrder" and symbol.exported is True for symbol in result.symbols)
    assert any(symbol.qualified_name == "OrdersController" and symbol.exported is True for symbol in result.symbols)
    assert any(
        reference.relationship_kind == "call"
        and reference.target == "renderOrder"
        and reference.source_symbol == "buildOrder"
        for reference in result.references
    )
    assert any(
        reference.relationship_kind == "route"
        and reference.target == "/api/orders/:orderId"
        and reference.source_symbol == "buildOrder"
        for reference in result.references
    )


def test_parse_common_language_symbols_instead_of_fallback(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    cases = {
        "main.go": ("func BuildInvoice(id string) string {\n  return id\n}\n", "go", "BuildInvoice", "function"),
        "lib.rs": ("pub fn build_invoice(id: &str) -> String {\n  id.to_string()\n}\n", "rust", "build_invoice", "function"),
        "OrderService.cs": ("public class OrderService {\n  public string BuildInvoice(string id) { return id; }\n}\n", "csharp", "OrderService", "class"),
        "tools.ps1": ("function Invoke-BuildInvoice {\n  param($Id)\n  return $Id\n}\n", "powershell", "Invoke-BuildInvoice", "function"),
    }

    for filename, (content, language, symbol_name, symbol_kind) in cases.items():
        path = root / filename
        path.write_text(content, encoding="utf-8")
        result = parse_code_file(path, root=root)
        assert result.metadata["language"] == language
        assert result.metadata["parser_status"] == "parsed"
        assert any(symbol.name == symbol_name and symbol.symbol_kind == symbol_kind for symbol in result.symbols)


def test_parse_csharp_controller_routes_tests_and_references(tmp_path):
    root = tmp_path / "repo"
    controllers = root / "src" / "Controllers"
    controllers.mkdir(parents=True)
    path = controllers / "OrdersController.cs"
    path.write_text(
        "\n".join(
            [
                "using Microsoft.AspNetCore.Mvc;",
                "using Xunit;",
                "",
                "namespace Demo.Api.Controllers;",
                "",
                "[ApiController]",
                "[Route(\"api/orders\")]",
                "public class OrdersController : ControllerBase",
                "{",
                "    private readonly OrderService _service;",
                "    public OrdersController(OrderService service) { _service = service; }",
                "",
                "    [HttpGet(\"{orderId}\")]",
                "    public ActionResult<OrderDto> GetOrder(string orderId)",
                "    {",
                "        return Ok(_service.GetOrder(orderId));",
                "    }",
                "}",
                "",
                "public class OrdersControllerTests",
                "{",
                "    [Fact]",
                "    public void GetOrder_returns_order()",
                "    {",
                "        Assert.NotNull(new OrdersController(new OrderService()));",
                "    }",
                "}",
            ]
        ),
        encoding="utf-8",
    )

    result = parse_code_file(path, root=root)

    assert result.metadata["language"] == "csharp"
    assert result.metadata["parser_status"] == "parsed"
    assert any(symbol.symbol_kind == "namespace" and symbol.qualified_name == "Demo.Api.Controllers" for symbol in result.symbols)
    assert any(symbol.symbol_kind == "class" and symbol.qualified_name == "Demo.Api.Controllers.OrdersController" for symbol in result.symbols)
    assert any(
        symbol.symbol_kind == "method"
        and symbol.qualified_name == "Demo.Api.Controllers.OrdersController.GetOrder"
        and symbol.metadata.get("routes") == ["api/orders/{orderId}"]
        for symbol in result.symbols
    )
    assert any(symbol.symbol_kind == "test" and symbol.name == "GetOrder_returns_order" for symbol in result.symbols)
    assert any(reference.relationship_kind == "using" and reference.target == "Microsoft.AspNetCore.Mvc" for reference in result.references)
    assert any(
        reference.relationship_kind == "route"
        and reference.target == "api/orders/{orderId}"
        and reference.source_symbol == "Demo.Api.Controllers.OrdersController.GetOrder"
        for reference in result.references
    )
    assert any(
        reference.relationship_kind == "call"
        and reference.target == "_service.GetOrder"
        and reference.source_symbol == "Demo.Api.Controllers.OrdersController.GetOrder"
        for reference in result.references
    )


def test_parse_frontend_markup_components_and_styles(tmp_path):
    root = tmp_path / "repo"
    web = root / "web"
    web.mkdir(parents=True)
    vue = web / "OrderCard.vue"
    vue.write_text(
        "\n".join(
            [
                "<template>",
                "  <article class=\"order-card\" @click=\"selectOrder\">",
                "    <OrderStatus :status=\"order.status\" />",
                "    <form action=\"/orders/search\"><input id=\"order-search\" /></form>",
                "  </article>",
                "</template>",
                "<script setup lang=\"ts\">",
                "import OrderStatus from './OrderStatus.vue';",
                "defineProps<{ order: Order }>();",
                "function selectOrder() {}",
                "</script>",
            ]
        ),
        encoding="utf-8",
    )
    scss = web / "orders.module.scss"
    scss.write_text(
        "\n".join(
            [
                ":root { --status-color: #127a5b; }",
                ".order-card { color: var(--status-color); }",
                "#order-search { border: 1px solid currentColor; }",
                "@keyframes orderPulse { from { opacity: 0; } to { opacity: 1; } }",
                "@media (min-width: 640px) { .order-card { display: grid; } }",
            ]
        ),
        encoding="utf-8",
    )

    vue_result = parse_code_file(vue, root=root)
    scss_result = parse_code_file(scss, root=root)

    assert vue_result.metadata["language"] == "vue"
    assert any(symbol.symbol_kind == "component" and symbol.name == "OrderCard" for symbol in vue_result.symbols)
    assert any(reference.relationship_kind == "component" and reference.target == "OrderStatus" for reference in vue_result.references)
    assert any(reference.relationship_kind == "event" and reference.target == "selectOrder" for reference in vue_result.references)
    assert any(reference.relationship_kind == "form_action" and reference.target == "/orders/search" for reference in vue_result.references)
    assert any(reference.relationship_kind == "selector" and reference.target == ".order-card" for reference in vue_result.references)
    assert any(reference.relationship_kind == "selector" and reference.target == "#order-search" for reference in vue_result.references)

    assert scss_result.metadata["language"] == "scss"
    assert any(symbol.symbol_kind == "selector" and symbol.name == ".order-card" for symbol in scss_result.symbols)
    assert any(symbol.symbol_kind == "selector" and symbol.name == "#order-search" for symbol in scss_result.symbols)
    assert any(symbol.symbol_kind == "custom_property" and symbol.name == "--status-color" for symbol in scss_result.symbols)
    assert any(symbol.symbol_kind == "keyframes" and symbol.name == "orderPulse" for symbol in scss_result.symbols)
    assert any(reference.relationship_kind == "media_query" and "(min-width: 640px)" in reference.target for reference in scss_result.references)
