// <auto-generated />
namespace FluxKnowledge.Integrations.Windows.NativeGoLive;

internal static partial class NativeGoLiveSqlBootstrapAuthorityContract
{
    internal const string BootstrapSourceSha256 = "b991bb0d1308a1f3af601c5873279ddddfa25cf92eeaba943480600bf792bfe4";
    internal const string SecurityBootstrapSha256 = "4caf0596fde411c6bbffeb4666ff941787fbda3a74dcfcf8043bda3a293f26a3";
    internal const string SigningCertificateName = "FluxKnowledgeNativeGoLiveCertificate";
    internal const string SigningCertificateLoginName = "FluxKnowledgeNativeGoLiveCertificateLogin";
    internal const string ProcedureManifestSha256 = "aa558b3269f879311cbfaaafc22acc6320023b02307eea90221a5f43a5364527";

    internal static string DefinitionSha256(string procedureName) => procedureName switch
    {
        "FluxKnowledgeNativeGoLiveCreate" => "1a4d9a8711cbc83e330f59814bfcc5eeea77260ac5e8ad74593481070bb16213",
        "FluxKnowledgeNativeGoLiveDrop" => "1d66fd3beafb537f12bc2e91655de2b68390500775056eb931018f80e20b7f66",
        "FluxKnowledgeNativeGoLiveManageAppPool" => "54647da826b0b5e3590f1abb28e620c461a1121975f85d46690325b2f455dcde",
        "FluxKnowledgeNativeGoLiveObserveAppPool" => "970fbd3d0f332311cdaeb2d1dd60a009315b61e4feffd363b9013b2a82bd6629",
        _ => throw new ArgumentOutOfRangeException(nameof(procedureName))
    };
}