// <auto-generated />
namespace FluxKnowledge.Integrations.Windows.NativeGoLive;

internal static partial class NativeGoLiveSqlBootstrapAuthorityContract
{
    internal const string BootstrapSourceSha256 = "039b96d087e538f3954b9be30ce753e002921a31b878bdcdeaab08902a2de10a";
    internal const string ProcedureManifestSha256 = "7cdbff5385e7289f48375ab7e5f4db3ede63122ca8288c3a9e8f8ddae28495b5";

    internal static string DefinitionSha256(string procedureName) => procedureName switch
    {
        "FluxKnowledgeNativeGoLiveCreate" => "a6e29165292dae603759feaa3494f3eb6a741f7b4033051eecc6a7e78d287bb2",
        "FluxKnowledgeNativeGoLiveDrop" => "1d66fd3beafb537f12bc2e91655de2b68390500775056eb931018f80e20b7f66",
        "FluxKnowledgeNativeGoLiveManageAppPool" => "6b1e601160471031bd9106c9b442c625d24442e97130f17ec7af05c382578ec4",
        "FluxKnowledgeNativeGoLiveObserveAppPool" => "49bc3649869da7c3a10b3af657700871dad46ab844ec7e4f3605c522e09c7de0",
        _ => throw new ArgumentOutOfRangeException(nameof(procedureName))
    };
}