// <auto-generated />
namespace FluxKnowledge.Integrations.Windows.NativeGoLive;

internal static partial class NativeGoLiveSqlBootstrapContract
{
    internal const string BootstrapSourceSha256 = "6f3e810d29cebd2ed7524314c7220f338bcaa5c9c35539e9a53ddc71ae03c145";
    internal const string ProcedureManifestSha256 = "3d88b254d985b1b58671cbd610134bbfeb2d0640f9508e2dfb9c906ce7595757";

    internal static string DefinitionSha256(string procedureName) => procedureName switch
    {
        "FluxKnowledgeNativeGoLiveCreate" => "fcb5bce2405dbbe12986d5a532ba6a8a9e91b23d0b2c523b00328c7c9eb53d83",
        "FluxKnowledgeNativeGoLiveDrop" => "1d66fd3beafb537f12bc2e91655de2b68390500775056eb931018f80e20b7f66",
        _ => throw new ArgumentOutOfRangeException(nameof(procedureName))
    };
}