// <auto-generated />
using System;
using FluxKnowledge.Infrastructure.SqlServer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluxKnowledge.Infrastructure.SqlServer.Persistence.Migrations
{
    [DbContext(typeof(FluxKnowledgeDbContext))]
    [Migration("20260729094809_AddGpuSchedulerOperationReceipts")]
    partial class AddGpuSchedulerOperationReceipts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("GpuMiniTaskCreatedSequence");

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.ArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("PipelineRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Artifacts");

                    b.HasIndex("PipelineRecordId", "SourceRevision", "Stage")
                        .IsUnique();

                    b.ToTable("Artifacts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Artifacts_ContentHash", "LEN([ContentHash]) = 64 AND [ContentHash] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");
                        });
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("PipelineRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRecordId", "OccurredAtUtc");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.GpuBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AdmissionGeneration")
                        .HasColumnType("bigint");

                    b.Property<string>("CapacitySlotKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("EstimatedBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastHeartbeatAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ModelRuntimeKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("PriorityLane")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SettingsFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("CapacitySlotKey");

                    b.ToTable("GpuBatches", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.GpuCapacitySlotEntity", b =>
                {
                    b.Property<string>("SlotKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ActiveBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastHeartbeatAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("OwnerKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("SlotKey");

                    b.HasIndex("ActiveBatchId");

                    b.HasIndex("State", "SlotKey");

                    b.ToTable("GpuCapacitySlots", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.GpuMiniTaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AdmissionGeneration")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("CreatedSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR [GpuMiniTaskCreatedSequence]");

                    b.Property<DateTimeOffset?>("DeferredUntilUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("EstimatedBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("ExecutionState")
                        .HasColumnType("int")
                        .HasColumnName("State");

                    b.Property<string>("HandoffLeaseOwner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ModelRuntimeKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ParentJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PriorityLane")
                        .HasColumnType("int");

                    b.Property<int>("ReservationAttemptCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SettingsFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ExecutionState", "DeferredUntilUtc");

                    b.HasIndex("ParentJobId", "SourceRevision");

                    b.HasIndex("ExecutionState", "PriorityLane", "CreatedSequence", "Id");

                    b.ToTable("GpuMiniTasks", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.GpuSchedulerOperationReceiptEntity", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<long?>("AdmissionGeneration")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapacitySlotKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Committed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int?>("EffectiveAdmissionReasons")
                        .HasColumnType("int");

                    b.Property<string>("OperationKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OwnerKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("WakeReasons")
                        .HasColumnType("int");

                    b.HasKey("OperationId");

                    b.HasIndex("OperationKind", "BatchId", "CapacitySlotKey", "AdmissionGeneration");

                    b.ToTable("GpuSchedulerOperationReceipts", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.GpuSchedulerStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("InFlightEffectiveAdmissionReasons")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("InFlightNextDeferredAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long?>("InFlightWakeGeneration")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("InFlightWakeOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InFlightWakeReasons")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("NextDeferredAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("PendingWakeReasons")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("WakeGeneration")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("GpuSchedulerState", null, t =>
                        {
                            t.HasCheckConstraint("CK_GpuSchedulerState_InFlightWake", "([InFlightWakeOperationId] IS NULL AND [InFlightWakeGeneration] IS NULL AND [InFlightWakeReasons] = 0 AND [InFlightNextDeferredAtUtc] IS NULL AND [InFlightEffectiveAdmissionReasons] IS NULL) OR ([InFlightWakeOperationId] IS NOT NULL AND [InFlightWakeGeneration] IS NOT NULL AND [InFlightEffectiveAdmissionReasons] IS NOT NULL)");

                            t.HasCheckConstraint("CK_GpuSchedulerState_Singleton", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.IndexGenerationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("Dimensions")
                        .HasColumnType("int");

                    b.Property<string>("IndexPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("MetadataChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("ModelFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("ValidatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("VectorCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("IndexGenerations", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.IndexGenerationVectorEntity", b =>
                {
                    b.Property<Guid>("GenerationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("VectorId")
                        .HasColumnType("bigint");

                    b.HasKey("GenerationId", "VectorId");

                    b.HasIndex("VectorId");

                    b.ToTable("IndexGenerationVectors", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.IndexStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid?>("ActiveIndexGenerationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveIndexGenerationId");

                    b.ToTable("IndexState", null, t =>
                        {
                            t.HasCheckConstraint("CK_IndexState_Singleton", "[Id] = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RowVersion = new byte[0],
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.JobAttemptEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("LeaseGeneration")
                        .HasColumnType("bigint");

                    b.Property<string>("LeaseOwner")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("JobAttempts", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.JobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("LeaseGeneration")
                        .HasColumnType("bigint");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("PipelineRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PublicState")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRecordId", "SourceRevision");

                    b.HasIndex("PublicState", "DueAtUtc");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("DispatchGeneration")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("LeaseGeneration")
                        .HasColumnType("bigint");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("PipelineRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("DispatchedAtUtc", "DueAtUtc");

                    b.HasIndex("PipelineRecordId", "SourceRevision");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CompletionCriteriaMet")
                        .HasColumnType("bit");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentRevisionRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RootLineageRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SourceIdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentRevisionRecordId");

                    b.HasIndex("RootLineageRecordId");

                    b.HasIndex("SourceIdentityId", "Revision")
                        .IsUnique();

                    b.ToTable("PipelineRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_PipelineRecords_ContentHash", "LEN([ContentHash]) = 64 AND [ContentHash] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");
                        });
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.SourceIdentityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StableKey")
                        .IsRequired()
                        .HasMaxLength(768)
                        .HasColumnType("nvarchar(768)");

                    b.HasKey("Id");

                    b.HasIndex("SourceKind", "StableKey")
                        .IsUnique();

                    b.ToTable("SourceIdentities", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.TextChunkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("StartOffset")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId", "Ordinal")
                        .IsUnique();

                    b.HasIndex("ArtifactId", "SourceRevision");

                    b.ToTable("TextChunks", null, t =>
                        {
                            t.HasCheckConstraint("CK_TextChunks_ContentHash", "LEN([ContentHash]) = 64 AND [ContentHash] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");
                        });
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.VectorEntity", b =>
                {
                    b.Property<long>("VectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VectorId"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("Dimensions")
                        .HasColumnType("int");

                    b.Property<Guid>("IndexGenerationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModelFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PayloadChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("TextChunkContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<long>("TextChunkId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Values")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("VectorId");

                    b.HasIndex("IndexGenerationId");

                    b.HasIndex("TextChunkId", "SourceRevision");

                    b.HasIndex("TextChunkId", "ModelFingerprint", "SourceRevision", "IndexGenerationId")
                        .IsUnique();

                    b.ToTable("Vectors", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vectors_PayloadChecksum", "LEN([PayloadChecksum]) = 64 AND [PayloadChecksum] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");

                            t.HasCheckConstraint("CK_Vectors_TextChunkContentHash", "LEN([TextChunkContentHash]) = 64 AND [TextChunkContentHash] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");
                        });
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.ArtifactEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", "PipelineRecord")
                        .WithMany()
                        .HasForeignKey("PipelineRecordId", "SourceRevision")
                        .HasPrincipalKey("Id", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PipelineRecord");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", "PipelineRecord")
                        .WithMany()
                        .HasForeignKey("PipelineRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PipelineRecord");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.GpuBatchEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.GpuCapacitySlotEntity", "CapacitySlot")
                        .WithMany()
                        .HasForeignKey("CapacitySlotKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CapacitySlot");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.GpuCapacitySlotEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.GpuBatchEntity", "ActiveBatch")
                        .WithMany()
                        .HasForeignKey("ActiveBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActiveBatch");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.GpuMiniTaskEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.GpuBatchEntity", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.JobEntity", "ParentJob")
                        .WithMany()
                        .HasForeignKey("ParentJobId", "SourceRevision")
                        .HasPrincipalKey("Id", "SourceRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("ParentJob");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.IndexGenerationVectorEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.IndexGenerationEntity", "Generation")
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.VectorEntity", "Vector")
                        .WithMany()
                        .HasForeignKey("VectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Generation");

                    b.Navigation("Vector");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.IndexStateEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.IndexGenerationEntity", "ActiveIndexGeneration")
                        .WithMany()
                        .HasForeignKey("ActiveIndexGenerationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActiveIndexGeneration");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.JobAttemptEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.JobEntity", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.JobEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", "PipelineRecord")
                        .WithMany()
                        .HasForeignKey("PipelineRecordId", "SourceRevision")
                        .HasPrincipalKey("Id", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PipelineRecord");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", "PipelineRecord")
                        .WithMany()
                        .HasForeignKey("PipelineRecordId", "SourceRevision")
                        .HasPrincipalKey("Id", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PipelineRecord");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", "ParentRevisionRecord")
                        .WithMany()
                        .HasForeignKey("ParentRevisionRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", null)
                        .WithMany()
                        .HasForeignKey("RootLineageRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.SourceIdentityEntity", "SourceIdentity")
                        .WithMany()
                        .HasForeignKey("SourceIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentRevisionRecord");

                    b.Navigation("SourceIdentity");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.TextChunkEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.ArtifactEntity", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId", "SourceRevision")
                        .HasPrincipalKey("Id", "SourceRevision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.VectorEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.IndexGenerationEntity", "IndexGeneration")
                        .WithMany()
                        .HasForeignKey("IndexGenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.TextChunkEntity", "TextChunk")
                        .WithMany()
                        .HasForeignKey("TextChunkId", "SourceRevision")
                        .HasPrincipalKey("Id", "SourceRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IndexGeneration");

                    b.Navigation("TextChunk");
                });
#pragma warning restore 612, 618
        }
    }
}
