// <auto-generated />
using System;
using FluxKnowledge.Infrastructure.SqlServer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluxKnowledge.Infrastructure.SqlServer.Persistence.Migrations
{
    [DbContext(typeof(FluxKnowledgeDbContext))]
    partial class FluxKnowledgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.ArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("PipelineRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Artifacts");

                    b.HasIndex("PipelineRecordId", "SourceRevision", "Stage")
                        .IsUnique();

                    b.ToTable("Artifacts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Artifacts_ContentHash", "LEN([ContentHash]) = 64 AND [ContentHash] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");
                        });
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("PipelineRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRecordId", "OccurredAtUtc");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.GpuMiniTaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AdmissionGeneration")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("EstimatedBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ModelRuntimeKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ParentJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PriorityLane")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SettingsFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ParentJobId");

                    b.HasIndex("State", "PriorityLane", "CreatedAtUtc");

                    b.ToTable("GpuMiniTasks", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.IndexGenerationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("Dimensions")
                        .HasColumnType("int");

                    b.Property<string>("IndexPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("MetadataChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("ModelFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("ValidatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("VectorCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("IndexGenerations", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.IndexStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid?>("ActiveIndexGenerationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveIndexGenerationId");

                    b.ToTable("IndexState", null, t =>
                        {
                            t.HasCheckConstraint("CK_IndexState_Singleton", "[Id] = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RowVersion = new byte[0],
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.JobAttemptEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("LeaseGeneration")
                        .HasColumnType("bigint");

                    b.Property<string>("LeaseOwner")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("JobAttempts", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.JobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("LeaseGeneration")
                        .HasColumnType("bigint");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("PipelineRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PublicState")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRecordId");

                    b.HasIndex("PublicState", "DueAtUtc");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("DispatchGeneration")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("LeaseGeneration")
                        .HasColumnType("bigint");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("PipelineRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PipelineRecordId");

                    b.HasIndex("DispatchedAtUtc", "DueAtUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CompletionCriteriaMet")
                        .HasColumnType("bit");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentRevisionRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RootLineageRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SourceIdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentRevisionRecordId");

                    b.HasIndex("RootLineageRecordId");

                    b.HasIndex("SourceIdentityId", "Revision")
                        .IsUnique();

                    b.ToTable("PipelineRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_PipelineRecords_ContentHash", "LEN([ContentHash]) = 64 AND [ContentHash] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");
                        });
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.SourceIdentityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StableKey")
                        .IsRequired()
                        .HasMaxLength(768)
                        .HasColumnType("nvarchar(768)");

                    b.HasKey("Id");

                    b.HasIndex("SourceKind", "StableKey")
                        .IsUnique();

                    b.ToTable("SourceIdentities", (string)null);
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.TextChunkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<int>("StartOffset")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId", "Ordinal")
                        .IsUnique();

                    b.ToTable("TextChunks", null, t =>
                        {
                            t.HasCheckConstraint("CK_TextChunks_ContentHash", "LEN([ContentHash]) = 64 AND [ContentHash] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");
                        });
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.VectorEntity", b =>
                {
                    b.Property<long>("VectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VectorId"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("Dimensions")
                        .HasColumnType("int");

                    b.Property<Guid>("IndexGenerationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModelFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("TextChunkId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Values")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("VectorId");

                    b.HasIndex("IndexGenerationId");

                    b.HasIndex("TextChunkId", "ModelFingerprint", "SourceRevision", "IndexGenerationId")
                        .IsUnique();

                    b.ToTable("Vectors", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vectors_ContentHash", "LEN([ContentHash]) = 64 AND [ContentHash] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");
                        });
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.ArtifactEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", "PipelineRecord")
                        .WithMany()
                        .HasForeignKey("PipelineRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PipelineRecord");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", "PipelineRecord")
                        .WithMany()
                        .HasForeignKey("PipelineRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PipelineRecord");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.GpuMiniTaskEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.JobEntity", "ParentJob")
                        .WithMany()
                        .HasForeignKey("ParentJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentJob");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.IndexStateEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.IndexGenerationEntity", "ActiveIndexGeneration")
                        .WithMany()
                        .HasForeignKey("ActiveIndexGenerationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActiveIndexGeneration");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.JobAttemptEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.JobEntity", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.JobEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", "PipelineRecord")
                        .WithMany()
                        .HasForeignKey("PipelineRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PipelineRecord");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", "PipelineRecord")
                        .WithMany()
                        .HasForeignKey("PipelineRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PipelineRecord");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", "ParentRevisionRecord")
                        .WithMany()
                        .HasForeignKey("ParentRevisionRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.PipelineRecordEntity", null)
                        .WithMany()
                        .HasForeignKey("RootLineageRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.SourceIdentityEntity", "SourceIdentity")
                        .WithMany()
                        .HasForeignKey("SourceIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentRevisionRecord");

                    b.Navigation("SourceIdentity");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.TextChunkEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.ArtifactEntity", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");
                });

            modelBuilder.Entity("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.VectorEntity", b =>
                {
                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.IndexGenerationEntity", "IndexGeneration")
                        .WithMany()
                        .HasForeignKey("IndexGenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FluxKnowledge.Infrastructure.SqlServer.Persistence.Entities.TextChunkEntity", "TextChunk")
                        .WithMany()
                        .HasForeignKey("TextChunkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IndexGeneration");

                    b.Navigation("TextChunk");
                });
#pragma warning restore 612, 618
        }
    }
}
