from __future__ import annotations

import ast
from dataclasses import dataclass, field, replace
import hashlib
import json
from pathlib import Path
import re
from typing import Any

from .redaction import redact_text


@dataclass(frozen=True)
class CodeChunk:
    chunk_index: int
    title: str
    body: str
    locator: str
    token_estimate: int
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CodeSymbol:
    name: str
    qualified_name: str
    symbol_kind: str
    language: str
    path: str
    line_start: int
    line_end: int
    chunk_index: int
    parent_symbol: str | None = None
    exported: bool | None = None
    signature: str | None = None
    parser_status: str = "parsed"
    confidence: float = 1.0
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CodeReference:
    relationship_kind: str
    target: str
    language: str
    path: str
    line_start: int
    line_end: int
    chunk_index: int
    source_symbol: str | None = None
    parser_status: str = "parsed"
    confidence: float = 0.8
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CodeIndexResult:
    chunks: tuple[CodeChunk, ...]
    symbols: tuple[CodeSymbol, ...] = ()
    references: tuple[CodeReference, ...] = ()
    metadata: dict[str, Any] = field(default_factory=dict)


CODE_LANGUAGE_EXTENSIONS: dict[str, str] = {
    ".py": "python",
    ".pyw": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".sql": "sql",
    ".go": "go",
    ".rs": "rust",
    ".java": "java",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".swift": "swift",
    ".c": "c",
    ".cc": "cpp",
    ".cpp": "cpp",
    ".cxx": "cpp",
    ".h": "c",
    ".hpp": "cpp",
    ".cs": "csharp",
    ".fs": "fsharp",
    ".fsx": "fsharp",
    ".vb": "visualbasic",
    ".rb": "ruby",
    ".php": "php",
    ".sh": "shell",
    ".bash": "shell",
    ".zsh": "shell",
    ".fish": "shell",
    ".bat": "batch",
    ".cmd": "batch",
    ".ps1": "powershell",
    ".psm1": "powershell",
    ".psd1": "powershell",
    ".tf": "terraform",
    ".tfvars": "terraform",
    ".hcl": "hcl",
    ".json": "json",
    ".jsonc": "jsonc",
    ".json5": "json5",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "toml",
    ".ini": "ini",
    ".cfg": "config",
    ".conf": "config",
    ".xml": "xml",
    ".graphql": "graphql",
    ".gql": "graphql",
    ".proto": "protobuf",
    ".patch": "diff",
    ".diff": "diff",
    ".ipynb": "notebook",
    ".csproj": "xml",
    ".fsproj": "xml",
    ".vbproj": "xml",
    ".sln": "solution",
}

DEVELOPER_ARTIFACT_NAMES: dict[str, str] = {
    ".env": "dotenv",
    ".env.example": "dotenv",
    "dockerfile": "dockerfile",
    "docker-compose.yml": "yaml",
    "docker-compose.yaml": "yaml",
    "compose.yml": "yaml",
    "compose.yaml": "yaml",
    "makefile": "make",
    "justfile": "just",
    "taskfile": "taskfile",
    "package.json": "json",
    "pyproject.toml": "toml",
    "requirements.txt": "requirements",
    "go.mod": "gomod",
    "go.sum": "gosum",
    "cargo.toml": "toml",
    "cargo.lock": "toml",
    "gemfile": "ruby",
    "rakefile": "ruby",
    "tsconfig.json": "json",
    "vite.config.ts": "typescript",
    "next.config.js": "javascript",
    "appsettings.json": "json",
    "openapi.yaml": "yaml",
    "openapi.yml": "yaml",
    "openapi.json": "json",
    "swagger.json": "json",
}

SQL_SYMBOL_RE = re.compile(
    r"\bCREATE\s+(?:OR\s+REPLACE\s+)?(?P<kind>TABLE|INDEX|VIEW|FUNCTION|PROCEDURE|TRIGGER)\s+(?:IF\s+NOT\s+EXISTS\s+)?(?P<name>[A-Za-z_][A-Za-z0-9_.$]*)",
    re.IGNORECASE,
)
JS_SYMBOL_RE = re.compile(
    r"(?P<kind>class|function)\s+(?P<name>[A-Za-z_$][A-Za-z0-9_$]*)|(?:const|let|var)\s+(?P<var>[A-Za-z_$][A-Za-z0-9_$]*)\s*=\s*(?:async\s*)?\([^)]*\)\s*=>",
)
ROUTE_RE = re.compile(
    r"\b(?:app|router)\.(?P<method>get|post|put|patch|delete)\s*\(\s*['\"](?P<route>[^'\"]+)['\"]\s*(?:,\s*(?P<handler>[A-Za-z_$][A-Za-z0-9_$]*))?"
)
EMAIL_RE = re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b")
GENERATED_MARKER_RE = re.compile(
    r"\b(auto[- ]?generated|generated by|code generated|do not edit|codegen|openapi generator|protoc)\b",
    re.IGNORECASE,
)
COMMON_LANGUAGE_SYMBOL_PATTERNS: dict[str, tuple[tuple[str, str, re.Pattern[str]], ...]] = {
    "go": (("function", "name", re.compile(r"\bfunc\s+(?:\([^)]+\)\s*)?(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\(")),),
    "rust": (("function", "name", re.compile(r"\b(?:pub\s+)?fn\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\(")),),
    "csharp": (
        ("class", "name", re.compile(r"\b(?:public|internal|private|protected|sealed|abstract|partial|\s)*class\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)")),
        (
            "method",
            "name",
            re.compile(
                r"\b(?:public|internal|private|protected|static|async|virtual|override|\s)+[A-Za-z_][A-Za-z0-9_<>,?\[\]]*\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\("
            ),
        ),
    ),
    "powershell": (("function", "name", re.compile(r"\bfunction\s+(?P<name>[A-Za-z_][A-Za-z0-9_-]*)\b", re.IGNORECASE)),),
}
JS_CALL_RE = re.compile(r"\b(?P<target>[A-Za-z_$][A-Za-z0-9_$]*)\s*\(")
JS_CALL_SKIP = {"if", "for", "while", "switch", "catch", "function", "return", "router", "app", "express"}


def is_code_like_path(path: str | Path) -> bool:
    file_path = Path(path)
    return file_path.suffix.lower() in CODE_LANGUAGE_EXTENSIONS or file_path.name.lower() in DEVELOPER_ARTIFACT_NAMES


def language_for_path(path: str | Path) -> str:
    file_path = Path(path)
    return DEVELOPER_ARTIFACT_NAMES.get(file_path.name.lower()) or CODE_LANGUAGE_EXTENSIONS.get(file_path.suffix.lower(), "text")


def parse_code_file(path: str | Path, *, root: str | Path | None = None) -> CodeIndexResult:
    file_path = Path(path)
    root_path = Path(root).resolve() if root is not None else file_path.parent.resolve()
    relative_path = _relative_path(file_path, root_path)
    language = language_for_path(file_path)
    raw_text = file_path.read_text(encoding="utf-8", errors="replace")

    if language == "python":
        return _parse_python(raw_text, relative_path=relative_path, language=language)
    if language == "sql":
        return _parse_sql(raw_text, relative_path=relative_path, language=language)
    if language in {"javascript", "typescript"}:
        return _parse_javascript_like(raw_text, relative_path=relative_path, language=language)
    if language == "notebook":
        return _parse_notebook(raw_text, relative_path=relative_path, language=language)
    if language in COMMON_LANGUAGE_SYMBOL_PATTERNS:
        return _parse_common_language(raw_text, relative_path=relative_path, language=language)
    if language in {"json", "jsonc", "json5", "yaml", "toml", "ini", "config", "xml", "graphql", "protobuf", "dockerfile", "make", "just", "taskfile", "requirements", "gomod", "gosum", "diff", "solution", "dotenv"}:
        return _parse_config_like(raw_text, relative_path=relative_path, language=language)
    return _fallback_result(raw_text, relative_path=relative_path, language=language)


def symbols_to_metadata(symbols: tuple[CodeSymbol, ...]) -> list[dict[str, Any]]:
    return [_symbol_metadata(symbol) for symbol in symbols]


def references_to_metadata(references: tuple[CodeReference, ...]) -> list[dict[str, Any]]:
    return [_reference_metadata(reference) for reference in references]


def _parse_python(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    try:
        tree = ast.parse(raw_text)
    except SyntaxError as exc:
        return _fallback_result(
            raw_text,
            relative_path=relative_path,
            language=language,
            diagnostics={"error_type": type(exc).__name__, "line": exc.lineno},
        )

    lines = raw_text.splitlines()
    chunks: list[CodeChunk] = []
    symbols: list[CodeSymbol] = []
    references: list[CodeReference] = []

    module_chunk = _chunk(
        raw_text,
        title=f"{relative_path}::module",
        relative_path=relative_path,
        language=language,
        symbol_kind="module",
        primary_symbol="module",
        relationship="definition",
        line_start=1,
        line_end=max(1, len(lines)),
        chunk_index=0,
    )
    chunks.append(module_chunk)
    references.extend(_python_references(tree, language=language, relative_path=relative_path, chunk_index=0, source_symbol=None))

    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            class_name = node.name
            chunk_index = len(chunks)
            chunks.append(
                _chunk_from_lines(
                    lines,
                    title=f"{relative_path}::{class_name}",
                    relative_path=relative_path,
                    language=language,
                    symbol_kind="class",
                    primary_symbol=class_name,
                    relationship="definition",
                    line_start=node.lineno,
                    line_end=getattr(node, "end_lineno", node.lineno),
                    chunk_index=chunk_index,
                )
            )
            symbols.append(
                _symbol(
                    node.name,
                    class_name,
                    "class",
                    language,
                    relative_path,
                    node.lineno,
                    getattr(node, "end_lineno", node.lineno),
                    chunk_index,
                    exported=not node.name.startswith("_"),
                )
            )
            references.extend(_python_references(node, language=language, relative_path=relative_path, chunk_index=chunk_index, source_symbol=class_name))
            for child in node.body:
                if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    qualified = f"{class_name}.{child.name}"
                    child_chunk_index = len(chunks)
                    chunks.append(
                        _chunk_from_lines(
                            lines,
                            title=f"{relative_path}::{qualified}",
                            relative_path=relative_path,
                            language=language,
                            symbol_kind="method",
                            primary_symbol=qualified,
                            relationship="definition",
                            line_start=child.lineno,
                            line_end=getattr(child, "end_lineno", child.lineno),
                            chunk_index=child_chunk_index,
                        )
                    )
                    symbols.append(
                        _symbol(
                            child.name,
                            qualified,
                            "method",
                            language,
                            relative_path,
                            child.lineno,
                            getattr(child, "end_lineno", child.lineno),
                            child_chunk_index,
                            parent_symbol=class_name,
                            exported=not child.name.startswith("_"),
                            signature=_python_signature(child),
                        )
                    )
                    references.extend(_python_references(child, language=language, relative_path=relative_path, chunk_index=child_chunk_index, source_symbol=qualified))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            routes = _python_routes(node)
            symbol_kind = _python_function_symbol_kind(node)
            chunk_relationship = "test" if symbol_kind == "test" else "fixture" if symbol_kind == "fixture" else "definition"
            chunk_index = len(chunks)
            chunks.append(
                _chunk_from_lines(
                    lines,
                    title=f"{relative_path}::{node.name}",
                    relative_path=relative_path,
                    language=language,
                    symbol_kind=symbol_kind,
                    primary_symbol=node.name,
                    relationship=chunk_relationship,
                    line_start=node.lineno,
                    line_end=getattr(node, "end_lineno", node.lineno),
                    chunk_index=chunk_index,
                    extra={"routes": routes} if routes else None,
                )
            )
            symbols.append(
                _symbol(
                    node.name,
                    node.name,
                    symbol_kind,
                    language,
                    relative_path,
                    node.lineno,
                    getattr(node, "end_lineno", node.lineno),
                    chunk_index,
                    exported=not node.name.startswith("_"),
                    signature=_python_signature(node),
                    metadata={"routes": routes} if routes else None,
                )
            )
            references.extend(
                _python_references(
                    node,
                    language=language,
                    relative_path=relative_path,
                    chunk_index=chunk_index,
                    source_symbol=node.name,
                    source_kind=symbol_kind,
                )
            )
            if symbol_kind == "test":
                references.extend(_python_fixture_references(node, language=language, relative_path=relative_path, chunk_index=chunk_index))

    return _result(chunks, symbols, references, language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _parse_sql(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    chunks: list[CodeChunk] = []
    symbols: list[CodeSymbol] = []
    statements = [part.strip() for part in raw_text.split(";") if part.strip()]
    line_offsets = _line_offsets(raw_text)
    relationship = "migration" if _is_migration_path(relative_path) else "definition"
    for statement in statements or [raw_text]:
        match = SQL_SYMBOL_RE.search(statement)
        symbol_kind = (match.group("kind").lower() if match else "statement")
        name = match.group("name").split(".")[-1] if match else f"statement_{len(chunks) + 1}"
        position = raw_text.find(statement)
        line_start = _line_for_offset(line_offsets, max(position, 0))
        line_end = line_start + max(0, statement.count("\n"))
        chunk_index = len(chunks)
        chunks.append(
            _chunk(
                statement,
                title=f"{relative_path}::{name}",
                relative_path=relative_path,
                language=language,
                symbol_kind=symbol_kind,
                primary_symbol=name,
                relationship=relationship,
                line_start=line_start,
                line_end=line_end,
                chunk_index=chunk_index,
            )
        )
        if match:
            symbols.append(_symbol(name, name, symbol_kind, language, relative_path, line_start, line_end, chunk_index))
    return _result(chunks, symbols, (), language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _parse_javascript_like(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    chunks: list[CodeChunk] = []
    symbols: list[CodeSymbol] = []
    references: list[CodeReference] = []
    lines = raw_text.splitlines()
    module_chunk = _chunk(
        raw_text,
        title=f"{relative_path}::module",
        relative_path=relative_path,
        language=language,
        symbol_kind="module",
        primary_symbol="module",
        relationship="definition",
        line_start=1,
        line_end=max(1, len(lines)),
        chunk_index=0,
    )
    chunks.append(module_chunk)
    for match in JS_SYMBOL_RE.finditer(raw_text):
        name = match.group("name") or match.group("var")
        symbol_kind = "class" if match.group("kind") == "class" else "function"
        line_start = raw_text[: match.start()].count("\n") + 1
        line_end = min(len(lines), line_start + 20)
        chunk_index = len(chunks)
        routes = [route.group("route") for route in ROUTE_RE.finditer(raw_text[max(0, match.start() - 160) : match.end() + 240])]
        chunk_relationship = "route" if routes else "definition"
        chunks.append(
            _chunk_from_lines(
                lines,
                title=f"{relative_path}::{name}",
                relative_path=relative_path,
                language=language,
                symbol_kind=symbol_kind,
                primary_symbol=name,
                relationship=chunk_relationship,
                line_start=line_start,
                line_end=line_end,
                chunk_index=chunk_index,
                extra={"routes": routes} if routes else None,
            )
        )
        symbols.append(
            _symbol(
                name,
                name,
                symbol_kind,
                language,
                relative_path,
                line_start,
                line_end,
                chunk_index,
                exported=not name.startswith("_"),
                metadata={"routes": routes} if routes else None,
            )
        )
        references.extend(_javascript_call_references(raw_text, match=match, symbol_name=name, language=language, relative_path=relative_path, chunk_index=chunk_index))
    for route in ROUTE_RE.finditer(raw_text):
        references.append(
            CodeReference(
                relationship_kind="route",
                target=route.group("route"),
                language=language,
                path=relative_path,
                line_start=raw_text[: route.start()].count("\n") + 1,
                line_end=raw_text[: route.start()].count("\n") + 1,
                chunk_index=0,
                source_symbol=route.group("handler"),
                metadata={"method": route.group("method").upper()},
            )
        )
    return _result(chunks, symbols, references, language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _parse_common_language(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    lines = raw_text.splitlines()
    line_offsets = _line_offsets(raw_text)
    chunks: list[CodeChunk] = []
    symbols: list[CodeSymbol] = []
    for symbol_kind, group_name, pattern in COMMON_LANGUAGE_SYMBOL_PATTERNS[language]:
        for match in pattern.finditer(raw_text):
            name = match.group(group_name)
            line_start = _line_for_offset(line_offsets, match.start())
            line_end = _common_symbol_line_end(lines, line_start)
            chunk_index = len(chunks)
            chunks.append(
                _chunk_from_lines(
                    lines,
                    title=f"{relative_path}::{name}",
                    relative_path=relative_path,
                    language=language,
                    symbol_kind=symbol_kind,
                    primary_symbol=name,
                    relationship="definition",
                    line_start=line_start,
                    line_end=line_end,
                    chunk_index=chunk_index,
                )
            )
            symbols.append(_symbol(name, name, symbol_kind, language, relative_path, line_start, line_end, chunk_index, exported=_common_symbol_exported(raw_text, match.start(), name)))
    if not chunks:
        return _fallback_result(raw_text, relative_path=relative_path, language=language)
    return _result(chunks, symbols, (), language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _parse_notebook(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    try:
        payload = json.loads(raw_text)
    except json.JSONDecodeError as exc:
        return _fallback_result(
            raw_text,
            relative_path=relative_path,
            language=language,
            diagnostics={"error_type": type(exc).__name__, "line": exc.lineno},
        )
    cells = payload.get("cells") if isinstance(payload, dict) else None
    if not isinstance(cells, list):
        return _fallback_result(
            raw_text,
            relative_path=relative_path,
            language=language,
            diagnostics={"error_type": "InvalidNotebook", "reason": "missing cells"},
        )
    chunks: list[CodeChunk] = []
    symbols: list[CodeSymbol] = []
    line_cursor = 1
    for index, cell in enumerate(cells):
        if not isinstance(cell, dict):
            continue
        source = cell.get("source", "")
        text = "".join(source) if isinstance(source, list) else str(source or "")
        cell_type = str(cell.get("cell_type") or "cell")
        line_count = max(1, len(text.splitlines()))
        primary_symbol = f"{cell_type}_cell_{index}"
        chunk_index = len(chunks)
        chunks.append(
            _chunk(
                text,
                title=f"{relative_path}::{primary_symbol}",
                relative_path=relative_path,
                language=language,
                symbol_kind="notebook_cell",
                primary_symbol=primary_symbol,
                relationship="definition",
                line_start=line_cursor,
                line_end=line_cursor + line_count - 1,
                chunk_index=chunk_index,
                extra={"cell_type": cell_type, "cell_index": index},
            )
        )
        symbols.append(
            _symbol(
                primary_symbol,
                primary_symbol,
                "notebook_cell",
                language,
                relative_path,
                line_cursor,
                line_cursor + line_count - 1,
                chunk_index,
                metadata={"cell_type": cell_type, "cell_index": index},
            )
        )
        line_cursor += line_count
    return _result(chunks, symbols, (), language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _parse_config_like(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    lines = raw_text.splitlines()
    chunk = _chunk(
        raw_text,
        title=f"{relative_path}::config",
        relative_path=relative_path,
        language=language,
        symbol_kind="config",
        primary_symbol=Path(relative_path).name,
        relationship="config",
        line_start=1,
        line_end=max(1, len(lines)),
        chunk_index=0,
    )
    symbol = _symbol(
        Path(relative_path).name,
        Path(relative_path).name,
        "config",
        language,
        relative_path,
        1,
        max(1, len(lines)),
        0,
    )
    return _result([chunk], [symbol], (), language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _fallback_result(
    raw_text: str,
    *,
    relative_path: str,
    language: str,
    diagnostics: dict[str, Any] | None = None,
) -> CodeIndexResult:
    chunk = _chunk(
        raw_text,
        title=f"{relative_path}::fallback",
        relative_path=relative_path,
        language=language,
        symbol_kind="fallback",
        primary_symbol=Path(relative_path).name,
        relationship="fallback",
        line_start=1,
        line_end=max(1, len(raw_text.splitlines())),
        chunk_index=0,
        parser_status="fallback",
    )
    metadata: dict[str, Any] = {
        "language": language,
        "parser_status": "fallback",
        "symbol_count": 0,
        "reference_count": 0,
    }
    generated = _is_generated_file(raw_text)
    if generated:
        metadata["generated"] = True
    if diagnostics:
        metadata["parser_diagnostics"] = diagnostics
    return CodeIndexResult(chunks=_mark_generated_chunks((chunk,), generated=generated), metadata=metadata)


def _is_migration_path(relative_path: str) -> bool:
    normalized = relative_path.replace("\\", "/").lower()
    return "/migrations/" in f"/{normalized}" or "migration" in Path(normalized).name


def _result(
    chunks: list[CodeChunk],
    symbols: list[CodeSymbol] | tuple[CodeSymbol, ...],
    references: list[CodeReference] | tuple[CodeReference, ...],
    *,
    language: str,
    parser_status: str,
    generated: bool = False,
) -> CodeIndexResult:
    metadata: dict[str, Any] = {
        "language": language,
        "parser_status": parser_status,
        "symbol_count": len(symbols),
        "reference_count": len(references),
    }
    if generated:
        metadata["generated"] = True
    return CodeIndexResult(
        chunks=_mark_generated_chunks(tuple(chunks), generated=generated),
        symbols=_mark_generated_symbols(tuple(symbols), generated=generated),
        references=_mark_generated_references(tuple(references), generated=generated),
        metadata=metadata,
    )


def _chunk_from_lines(
    lines: list[str],
    *,
    title: str,
    relative_path: str,
    language: str,
    symbol_kind: str,
    primary_symbol: str,
    relationship: str,
    line_start: int,
    line_end: int,
    chunk_index: int,
    extra: dict[str, Any] | None = None,
) -> CodeChunk:
    body = "\n".join(lines[max(0, line_start - 1) : max(line_start, line_end)])
    return _chunk(
        body,
        title=title,
        relative_path=relative_path,
        language=language,
        symbol_kind=symbol_kind,
        primary_symbol=primary_symbol,
        relationship=relationship,
        line_start=line_start,
        line_end=line_end,
        chunk_index=chunk_index,
        extra=extra,
    )


def _chunk(
    text: str,
    *,
    title: str,
    relative_path: str,
    language: str,
    symbol_kind: str,
    primary_symbol: str,
    relationship: str,
    line_start: int,
    line_end: int,
    chunk_index: int,
    parser_status: str = "parsed",
    extra: dict[str, Any] | None = None,
) -> CodeChunk:
    redacted, _ = redact_text(text)
    redacted = EMAIL_RE.sub("[REDACTED:email]", redacted)
    metadata: dict[str, Any] = {
        "code": {
            "language": language,
            "primary_symbol": primary_symbol,
            "symbol_kind": symbol_kind,
            "relationship": relationship,
            "range": {"line_start": int(line_start), "line_end": int(line_end)},
            "parser_status": parser_status,
            "source_path": relative_path,
        },
        "language": language,
        "symbol_kind": symbol_kind,
        "relationship": relationship,
        "parser_status": parser_status,
    }
    if extra:
        metadata["code"].update(extra)
        metadata.update(extra)
    return CodeChunk(
        chunk_index=chunk_index,
        title=title,
        body=redacted.strip(),
        locator=f"line:{line_start}-{line_end}",
        token_estimate=max(1, len(redacted.split())),
        metadata=metadata,
    )


def _is_generated_file(raw_text: str) -> bool:
    head = "\n".join(raw_text.splitlines()[:20])
    return bool(GENERATED_MARKER_RE.search(head))


def _mark_generated_chunks(chunks: tuple[CodeChunk, ...], *, generated: bool) -> tuple[CodeChunk, ...]:
    if not generated:
        return chunks
    marked: list[CodeChunk] = []
    for chunk in chunks:
        code = dict(chunk.metadata.get("code") or {})
        code["generated"] = True
        marked.append(replace(chunk, metadata={**chunk.metadata, "generated": True, "code": code}))
    return tuple(marked)


def _mark_generated_symbols(symbols: tuple[CodeSymbol, ...], *, generated: bool) -> tuple[CodeSymbol, ...]:
    if not generated:
        return symbols
    return tuple(replace(symbol, metadata={**symbol.metadata, "generated": True}) for symbol in symbols)


def _mark_generated_references(references: tuple[CodeReference, ...], *, generated: bool) -> tuple[CodeReference, ...]:
    if not generated:
        return references
    return tuple(replace(reference, metadata={**reference.metadata, "generated": True}) for reference in references)


def _symbol(
    name: str,
    qualified_name: str,
    symbol_kind: str,
    language: str,
    relative_path: str,
    line_start: int,
    line_end: int,
    chunk_index: int,
    *,
    parent_symbol: str | None = None,
    exported: bool | None = None,
    signature: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> CodeSymbol:
    return CodeSymbol(
        name=name,
        qualified_name=qualified_name,
        symbol_kind=symbol_kind,
        language=language,
        path=relative_path,
        line_start=int(line_start),
        line_end=int(line_end),
        chunk_index=int(chunk_index),
        parent_symbol=parent_symbol,
        exported=exported,
        signature=signature,
        metadata=metadata or {},
    )


def _symbol_metadata(symbol: CodeSymbol) -> dict[str, Any]:
    data = {
        "name": symbol.name,
        "qualified_name": symbol.qualified_name,
        "symbol_kind": symbol.symbol_kind,
        "language": symbol.language,
        "path": symbol.path,
        "line_start": symbol.line_start,
        "line_end": symbol.line_end,
        "chunk_index": symbol.chunk_index,
        "parent_symbol": symbol.parent_symbol,
        "exported": symbol.exported,
        "signature": symbol.signature,
        "parser_status": symbol.parser_status,
        "confidence": symbol.confidence,
        "metadata": symbol.metadata,
    }
    return {key: value for key, value in data.items() if value is not None}


def _reference_metadata(reference: CodeReference) -> dict[str, Any]:
    data = {
        "relationship_kind": reference.relationship_kind,
        "target": reference.target,
        "language": reference.language,
        "path": reference.path,
        "line_start": reference.line_start,
        "line_end": reference.line_end,
        "chunk_index": reference.chunk_index,
        "source_symbol": reference.source_symbol,
        "parser_status": reference.parser_status,
        "confidence": reference.confidence,
        "metadata": reference.metadata,
    }
    return {key: value for key, value in data.items() if value is not None}


def _python_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    names = [arg.arg for arg in node.args.posonlyargs + node.args.args + node.args.kwonlyargs]
    if node.args.vararg:
        names.append(f"*{node.args.vararg.arg}")
    if node.args.kwarg:
        names.append(f"**{node.args.kwarg.arg}")
    return f"{node.name}({', '.join(names)})"


def _python_routes(node: ast.FunctionDef | ast.AsyncFunctionDef) -> list[str]:
    routes: list[str] = []
    for decorator in node.decorator_list:
        if not isinstance(decorator, ast.Call):
            continue
        func = decorator.func
        if not isinstance(func, ast.Attribute) or func.attr not in {"get", "post", "put", "patch", "delete"}:
            continue
        if decorator.args and isinstance(decorator.args[0], ast.Constant) and isinstance(decorator.args[0].value, str):
            routes.append(decorator.args[0].value)
    return routes


def _python_function_symbol_kind(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    if _has_pytest_fixture_decorator(node):
        return "fixture"
    if node.name.startswith("test_"):
        return "test"
    return "function"


def _has_pytest_fixture_decorator(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    for decorator in node.decorator_list:
        func = decorator.func if isinstance(decorator, ast.Call) else decorator
        if isinstance(func, ast.Name) and func.id == "fixture":
            return True
        if isinstance(func, ast.Attribute) and func.attr == "fixture":
            return True
    return False


def _python_references(
    node: ast.AST,
    *,
    language: str,
    relative_path: str,
    chunk_index: int,
    source_symbol: str | None,
    source_kind: str | None = None,
) -> list[CodeReference]:
    references: list[CodeReference] = []
    for child in ast.walk(node):
        if isinstance(child, ast.ImportFrom):
            module = child.module or ""
            for alias in child.names:
                target = f"{module}.{alias.name}" if module else alias.name
                references.append(
                    CodeReference(
                        relationship_kind="import",
                        target=target,
                        language=language,
                        path=relative_path,
                        line_start=child.lineno,
                        line_end=child.lineno,
                        chunk_index=chunk_index,
                        source_symbol=source_symbol,
                        confidence=1.0,
                    )
                )
        elif isinstance(child, ast.Import):
            for alias in child.names:
                references.append(
                    CodeReference(
                        relationship_kind="import",
                        target=alias.name,
                        language=language,
                        path=relative_path,
                        line_start=child.lineno,
                        line_end=child.lineno,
                        chunk_index=chunk_index,
                        source_symbol=source_symbol,
                        confidence=1.0,
                    )
                )
        elif isinstance(child, ast.Call):
            target = _call_target(child.func)
            if target:
                references.append(
                    CodeReference(
                        relationship_kind="test" if source_kind == "test" else "call",
                        target=target,
                        language=language,
                        path=relative_path,
                        line_start=getattr(child, "lineno", 1),
                        line_end=getattr(child, "end_lineno", getattr(child, "lineno", 1)),
                        chunk_index=chunk_index,
                        source_symbol=source_symbol,
                    )
                )
    return _dedupe_references(references)


def _python_fixture_references(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    *,
    language: str,
    relative_path: str,
    chunk_index: int,
) -> list[CodeReference]:
    return [
        CodeReference(
            relationship_kind="fixture",
            target=arg.arg,
            language=language,
            path=relative_path,
            line_start=node.lineno,
            line_end=getattr(node, "end_lineno", node.lineno),
            chunk_index=chunk_index,
            source_symbol=node.name,
            confidence=1.0,
        )
        for arg in node.args.args
        if arg.arg != "self"
    ]


def _javascript_call_references(
    raw_text: str,
    *,
    match: re.Match[str],
    symbol_name: str,
    language: str,
    relative_path: str,
    chunk_index: int,
) -> list[CodeReference]:
    snippet = raw_text[match.end() : match.end() + 500]
    references: list[CodeReference] = []
    for call in JS_CALL_RE.finditer(snippet):
        target = call.group("target")
        if target == symbol_name or target in JS_CALL_SKIP:
            continue
        offset = match.end() + call.start()
        line = raw_text[:offset].count("\n") + 1
        references.append(
            CodeReference(
                relationship_kind="call",
                target=target,
                language=language,
                path=relative_path,
                line_start=line,
                line_end=line,
                chunk_index=chunk_index,
                source_symbol=symbol_name,
            )
        )
    return _dedupe_references(references)


def _common_symbol_line_end(lines: list[str], line_start: int) -> int:
    if not lines:
        return 1
    return min(len(lines), max(line_start, line_start + 20))


def _common_symbol_exported(raw_text: str, start: int, name: str) -> bool | None:
    prefix = raw_text[max(0, start - 32) : start].lower()
    return bool("pub " in prefix or "public " in prefix or "export " in prefix or name[:1].isupper())


def _call_target(func: ast.AST) -> str | None:
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        base = _call_target(func.value)
        return f"{base}.{func.attr}" if base else func.attr
    return None


def _dedupe_references(references: list[CodeReference]) -> list[CodeReference]:
    seen: set[tuple[str, str, int, str | None]] = set()
    result: list[CodeReference] = []
    for reference in references:
        key = (reference.relationship_kind, reference.target, reference.line_start, reference.source_symbol)
        if key in seen:
            continue
        seen.add(key)
        result.append(reference)
    return result


def _line_offsets(text: str) -> list[int]:
    offsets = [0]
    for match in re.finditer("\n", text):
        offsets.append(match.end())
    return offsets


def _line_for_offset(offsets: list[int], offset: int) -> int:
    line = 1
    for index, value in enumerate(offsets, start=1):
        if value > offset:
            break
        line = index
    return line


def _relative_path(path: Path, root: Path) -> str:
    resolved = path.resolve()
    try:
        return resolved.relative_to(root).as_posix()
    except ValueError:
        return resolved.name


def scope_hash(root_name: str | None, path: str) -> str:
    return hashlib.sha256(f"{root_name or ''}:{path}".encode("utf-8")).hexdigest()[:16]
