from __future__ import annotations

import ast
from dataclasses import dataclass, field, replace
import hashlib
import json
from pathlib import Path
import re
from typing import Any

from .redaction import redact_text
from .text_safety import read_text_with_bom


@dataclass(frozen=True)
class CodeChunk:
    chunk_index: int
    title: str
    body: str
    locator: str
    token_estimate: int
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CodeSymbol:
    name: str
    qualified_name: str
    symbol_kind: str
    language: str
    path: str
    line_start: int
    line_end: int
    chunk_index: int
    parent_symbol: str | None = None
    exported: bool | None = None
    signature: str | None = None
    parser_status: str = "parsed"
    confidence: float = 1.0
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CodeReference:
    relationship_kind: str
    target: str
    language: str
    path: str
    line_start: int
    line_end: int
    chunk_index: int
    source_symbol: str | None = None
    parser_status: str = "parsed"
    confidence: float = 0.8
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CodeIndexResult:
    chunks: tuple[CodeChunk, ...]
    symbols: tuple[CodeSymbol, ...] = ()
    references: tuple[CodeReference, ...] = ()
    metadata: dict[str, Any] = field(default_factory=dict)


CODE_LANGUAGE_EXTENSIONS: dict[str, str] = {
    ".py": "python",
    ".pyw": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".html": "html",
    ".htm": "html",
    ".css": "css",
    ".scss": "scss",
    ".sass": "sass",
    ".less": "less",
    ".vue": "vue",
    ".svelte": "svelte",
    ".astro": "astro",
    ".razor": "razor",
    ".cshtml": "razor",
    ".sql": "sql",
    ".go": "go",
    ".rs": "rust",
    ".java": "java",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".swift": "swift",
    ".c": "c",
    ".cc": "cpp",
    ".cpp": "cpp",
    ".cxx": "cpp",
    ".h": "c",
    ".hpp": "cpp",
    ".cs": "csharp",
    ".fs": "fsharp",
    ".fsx": "fsharp",
    ".vb": "visualbasic",
    ".rb": "ruby",
    ".php": "php",
    ".sh": "shell",
    ".bash": "shell",
    ".zsh": "shell",
    ".fish": "shell",
    ".bat": "batch",
    ".cmd": "batch",
    ".ps1": "powershell",
    ".psm1": "powershell",
    ".psd1": "powershell",
    ".tf": "terraform",
    ".tfvars": "terraform",
    ".hcl": "hcl",
    ".json": "json",
    ".jsonc": "jsonc",
    ".json5": "json5",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "toml",
    ".ini": "ini",
    ".cfg": "config",
    ".conf": "config",
    ".xml": "xml",
    ".graphql": "graphql",
    ".gql": "graphql",
    ".proto": "protobuf",
    ".patch": "diff",
    ".diff": "diff",
    ".ipynb": "notebook",
    ".csproj": "xml",
    ".fsproj": "xml",
    ".vbproj": "xml",
    ".props": "xml",
    ".targets": "xml",
    ".sln": "solution",
}

DEVELOPER_ARTIFACT_NAMES: dict[str, str] = {
    ".env": "dotenv",
    ".env.example": "dotenv",
    "dockerfile": "dockerfile",
    "docker-compose.yml": "yaml",
    "docker-compose.yaml": "yaml",
    "compose.yml": "yaml",
    "compose.yaml": "yaml",
    "makefile": "make",
    "justfile": "just",
    "taskfile": "taskfile",
    "package.json": "json",
    "pyproject.toml": "toml",
    "requirements.txt": "requirements",
    "go.mod": "gomod",
    "go.sum": "gosum",
    "cargo.toml": "toml",
    "cargo.lock": "toml",
    "gemfile": "ruby",
    "rakefile": "ruby",
    "tsconfig.json": "json",
    "vite.config.ts": "typescript",
    "next.config.js": "javascript",
    "appsettings.json": "json",
    "openapi.yaml": "yaml",
    "openapi.yml": "yaml",
    "openapi.json": "json",
    "swagger.json": "json",
    ".editorconfig": "config",
}

SQL_SYMBOL_RE = re.compile(
    r"\bCREATE\s+(?:OR\s+REPLACE\s+)?(?P<kind>TABLE|INDEX|VIEW|FUNCTION|PROCEDURE|TRIGGER)\s+(?:IF\s+NOT\s+EXISTS\s+)?(?P<name>[A-Za-z_][A-Za-z0-9_.$]*)",
    re.IGNORECASE,
)
JS_SYMBOL_RE = re.compile(
    r"(?P<kind>class|function)\s+(?P<name>[A-Za-z_$][A-Za-z0-9_$]*)|(?:const|let|var)\s+(?P<var>[A-Za-z_$][A-Za-z0-9_$]*)\s*=\s*(?:async\s*)?\([^)]*\)\s*=>",
)
ROUTE_RE = re.compile(
    r"\b(?:app|router)\.(?P<method>get|post|put|patch|delete)\s*\(\s*['\"](?P<route>[^'\"]+)['\"]\s*(?:,\s*(?P<handler>[A-Za-z_$][A-Za-z0-9_$]*))?"
)
EMAIL_RE = re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b")
GENERATED_MARKER_RE = re.compile(
    r"\b(auto[- ]?generated|generated by|code generated|do not edit|codegen|openapi generator|protoc)\b",
    re.IGNORECASE,
)
COMMON_LANGUAGE_SYMBOL_PATTERNS: dict[str, tuple[tuple[str, str, re.Pattern[str]], ...]] = {
    "go": (("function", "name", re.compile(r"\bfunc\s+(?:\([^)]+\)\s*)?(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\(")),),
    "rust": (("function", "name", re.compile(r"\b(?:pub\s+)?fn\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\(")),),
    "csharp": (
        ("class", "name", re.compile(r"\b(?:public|internal|private|protected|sealed|abstract|partial|\s)*class\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)")),
        (
            "method",
            "name",
            re.compile(
                r"\b(?:public|internal|private|protected|static|async|virtual|override|\s)+[A-Za-z_][A-Za-z0-9_<>,?\[\]]*\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\("
            ),
        ),
    ),
    "powershell": (("function", "name", re.compile(r"\bfunction\s+(?P<name>[A-Za-z_][A-Za-z0-9_-]*)\b", re.IGNORECASE)),),
}
JS_CALL_RE = re.compile(r"\b(?P<target>[A-Za-z_$][A-Za-z0-9_$]*)\s*\(")
JS_CALL_SKIP = {"if", "for", "while", "switch", "catch", "function", "return", "router", "app", "express"}
CS_TYPE_RE = re.compile(
    r"\b(?:public|internal|private|protected|sealed|abstract|partial|static|\s)*"
    r"(?P<kind>class|interface|record|struct|enum)\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)"
)
CS_METHOD_RE = re.compile(
    r"\b(?:public|internal|private|protected|static|async|virtual|override|sealed|partial|\s)+"
    r"(?P<return_type>[A-Za-z_][A-Za-z0-9_<>,?.\[\]]*)\s+"
    r"(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\("
)
CS_NAMESPACE_RE = re.compile(r"\bnamespace\s+(?P<name>[A-Za-z_][A-Za-z0-9_.]*)\s*[;{]")
CS_USING_RE = re.compile(r"^\s*using\s+(?P<target>[A-Za-z_][A-Za-z0-9_.]*)\s*;", re.MULTILINE)
CS_ROUTE_ATTR_RE = re.compile(r"\[(?P<attr>Route|HttpGet|HttpPost|HttpPut|HttpPatch|HttpDelete)(?:\s*\(\s*\"(?P<route>[^\"]*)\"\s*\))?", re.IGNORECASE)
CS_TEST_ATTR_RE = re.compile(r"\[(?:Fact|Theory|Test|TestMethod)\b", re.IGNORECASE)
CS_CALL_RE = re.compile(r"\b(?P<target>(?:[A-Za-z_][A-Za-z0-9_]*\.)?[A-Za-z_][A-Za-z0-9_]*)\s*\(")
CS_CALL_SKIP = {"if", "for", "foreach", "while", "switch", "catch", "return", "new", "typeof", "nameof", "using"}
FRONTEND_COMPONENT_TAG_RE = re.compile(r"<(?P<name>[A-Z][A-Za-z0-9_]*)\b")
FRONTEND_IMPORT_RE = re.compile(r"\bimport\s+(?P<name>[A-Za-z_$][A-Za-z0-9_$]*)\s+from\s+['\"](?P<target>[^'\"]+)['\"]")
FRONTEND_EVENT_RE = re.compile(r"@(?P<event>[A-Za-z0-9_:-]+)\s*=\s*['\"](?P<handler>[^'\"]+)['\"]")
FRONTEND_ACTION_RE = re.compile(r"<form\b[^>]*\baction\s*=\s*['\"](?P<target>[^'\"]+)['\"]", re.IGNORECASE)
HTML_CLASS_RE = re.compile(r"\bclass\s*=\s*['\"](?P<value>[^'\"]+)['\"]", re.IGNORECASE)
HTML_ID_RE = re.compile(r"\bid\s*=\s*['\"](?P<value>[^'\"]+)['\"]", re.IGNORECASE)
CSS_CLASS_RE = re.compile(r"(?<![\w-])\.(?P<name>[A-Za-z_-][A-Za-z0-9_-]*)\b")
CSS_ID_RE = re.compile(r"(?<![\w-])#(?P<name>[A-Za-z_-][A-Za-z0-9_-]*)\b")
CSS_CUSTOM_PROPERTY_RE = re.compile(r"(?P<name>--[A-Za-z0-9_-]+)\s*:")
CSS_KEYFRAMES_RE = re.compile(r"@keyframes\s+(?P<name>[A-Za-z_][A-Za-z0-9_-]*)", re.IGNORECASE)
CSS_MEDIA_RE = re.compile(r"@media\s+(?P<query>[^{]+)\{", re.IGNORECASE)


def is_code_like_path(path: str | Path) -> bool:
    file_path = Path(path)
    return file_path.suffix.lower() in CODE_LANGUAGE_EXTENSIONS or file_path.name.lower() in DEVELOPER_ARTIFACT_NAMES


def language_for_path(path: str | Path) -> str:
    file_path = Path(path)
    return DEVELOPER_ARTIFACT_NAMES.get(file_path.name.lower()) or CODE_LANGUAGE_EXTENSIONS.get(file_path.suffix.lower(), "text")


def parse_code_file(path: str | Path, *, root: str | Path | None = None, relative_path: str | None = None) -> CodeIndexResult:
    file_path = Path(path)
    if relative_path is None:
        root_path = Path(root).resolve() if root is not None else file_path.parent.resolve()
        relative_path = _relative_path(file_path, root_path)
    else:
        relative_path = _normalise_relative_path(relative_path)
    language = language_for_path(file_path)
    raw_text = read_text_with_bom(file_path)

    if language == "python":
        return _parse_python(raw_text, relative_path=relative_path, language=language)
    if language == "sql":
        return _parse_sql(raw_text, relative_path=relative_path, language=language)
    if language in {"javascript", "typescript"}:
        return _parse_javascript_like(raw_text, relative_path=relative_path, language=language)
    if language == "csharp":
        return _parse_csharp(raw_text, relative_path=relative_path, language=language)
    if language in {"html", "vue", "svelte", "astro", "razor"}:
        return _parse_frontend_markup(raw_text, relative_path=relative_path, language=language)
    if language in {"css", "scss", "sass", "less"}:
        return _parse_stylesheet(raw_text, relative_path=relative_path, language=language)
    if language == "notebook":
        return _parse_notebook(raw_text, relative_path=relative_path, language=language)
    if language in COMMON_LANGUAGE_SYMBOL_PATTERNS:
        return _parse_common_language(raw_text, relative_path=relative_path, language=language)
    if language in {"json", "jsonc", "json5", "yaml", "toml", "ini", "config", "xml", "graphql", "protobuf", "dockerfile", "make", "just", "taskfile", "requirements", "gomod", "gosum", "diff", "solution", "dotenv"}:
        return _parse_config_like(raw_text, relative_path=relative_path, language=language)
    return _fallback_result(raw_text, relative_path=relative_path, language=language)


def symbols_to_metadata(symbols: tuple[CodeSymbol, ...]) -> list[dict[str, Any]]:
    return [_symbol_metadata(symbol) for symbol in symbols]


def references_to_metadata(references: tuple[CodeReference, ...]) -> list[dict[str, Any]]:
    return [_reference_metadata(reference) for reference in references]


def _parse_python(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    try:
        tree = ast.parse(raw_text)
    except SyntaxError as exc:
        return _fallback_result(
            raw_text,
            relative_path=relative_path,
            language=language,
            diagnostics={"error_type": type(exc).__name__, "line": exc.lineno},
        )

    lines = raw_text.splitlines()
    chunks: list[CodeChunk] = []
    symbols: list[CodeSymbol] = []
    references: list[CodeReference] = []

    module_chunk = _chunk(
        raw_text,
        title=f"{relative_path}::module",
        relative_path=relative_path,
        language=language,
        symbol_kind="module",
        primary_symbol="module",
        relationship="definition",
        line_start=1,
        line_end=max(1, len(lines)),
        chunk_index=0,
    )
    chunks.append(module_chunk)
    references.extend(_python_references(tree, language=language, relative_path=relative_path, chunk_index=0, source_symbol=None))

    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            class_name = node.name
            class_metadata = _python_class_metadata(node)
            chunk_index = len(chunks)
            chunks.append(
                _chunk_from_lines(
                    lines,
                    title=f"{relative_path}::{class_name}",
                    relative_path=relative_path,
                    language=language,
                    symbol_kind="class",
                    primary_symbol=class_name,
                    relationship="definition",
                    line_start=node.lineno,
                    line_end=getattr(node, "end_lineno", node.lineno),
                    chunk_index=chunk_index,
                    extra=class_metadata or None,
                )
            )
            symbols.append(
                _symbol(
                    node.name,
                    class_name,
                    "class",
                    language,
                    relative_path,
                    node.lineno,
                    getattr(node, "end_lineno", node.lineno),
                    chunk_index,
                    exported=not node.name.startswith("_"),
                    metadata=class_metadata or None,
                )
            )
            references.extend(
                _python_class_references(
                    node,
                    language=language,
                    relative_path=relative_path,
                    chunk_index=chunk_index,
                    source_symbol=class_name,
                )
            )
            references.extend(_python_references(node, language=language, relative_path=relative_path, chunk_index=chunk_index, source_symbol=class_name))
            for child in node.body:
                if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    qualified = f"{class_name}.{child.name}"
                    child_chunk_index = len(chunks)
                    chunks.append(
                        _chunk_from_lines(
                            lines,
                            title=f"{relative_path}::{qualified}",
                            relative_path=relative_path,
                            language=language,
                            symbol_kind="method",
                            primary_symbol=qualified,
                            relationship="definition",
                            line_start=child.lineno,
                            line_end=getattr(child, "end_lineno", child.lineno),
                            chunk_index=child_chunk_index,
                        )
                    )
                    symbols.append(
                        _symbol(
                            child.name,
                            qualified,
                            "method",
                            language,
                            relative_path,
                            child.lineno,
                            getattr(child, "end_lineno", child.lineno),
                            child_chunk_index,
                            parent_symbol=class_name,
                            exported=not child.name.startswith("_"),
                            signature=_python_signature(child),
                        )
                    )
                    references.extend(_python_references(child, language=language, relative_path=relative_path, chunk_index=child_chunk_index, source_symbol=qualified))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            routes = _python_routes(node)
            symbol_kind = _python_function_symbol_kind(node)
            chunk_relationship = "test" if symbol_kind == "test" else "fixture" if symbol_kind == "fixture" else "definition"
            chunk_index = len(chunks)
            chunks.append(
                _chunk_from_lines(
                    lines,
                    title=f"{relative_path}::{node.name}",
                    relative_path=relative_path,
                    language=language,
                    symbol_kind=symbol_kind,
                    primary_symbol=node.name,
                    relationship=chunk_relationship,
                    line_start=node.lineno,
                    line_end=getattr(node, "end_lineno", node.lineno),
                    chunk_index=chunk_index,
                    extra={"routes": routes} if routes else None,
                )
            )
            symbols.append(
                _symbol(
                    node.name,
                    node.name,
                    symbol_kind,
                    language,
                    relative_path,
                    node.lineno,
                    getattr(node, "end_lineno", node.lineno),
                    chunk_index,
                    exported=not node.name.startswith("_"),
                    signature=_python_signature(node),
                    metadata={"routes": routes} if routes else None,
                )
            )
            references.extend(
                _python_references(
                    node,
                    language=language,
                    relative_path=relative_path,
                    chunk_index=chunk_index,
                    source_symbol=node.name,
                    source_kind=symbol_kind,
                )
            )
            if symbol_kind == "test":
                references.extend(_python_fixture_references(node, language=language, relative_path=relative_path, chunk_index=chunk_index))

    return _result(chunks, symbols, references, language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _parse_sql(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    chunks: list[CodeChunk] = []
    symbols: list[CodeSymbol] = []
    statements = [part.strip() for part in raw_text.split(";") if part.strip()]
    line_offsets = _line_offsets(raw_text)
    relationship = "migration" if _is_migration_path(relative_path) else "definition"
    for statement in statements or [raw_text]:
        match = SQL_SYMBOL_RE.search(statement)
        symbol_kind = (match.group("kind").lower() if match else "statement")
        name = match.group("name").split(".")[-1] if match else f"statement_{len(chunks) + 1}"
        position = raw_text.find(statement)
        line_start = _line_for_offset(line_offsets, max(position, 0))
        line_end = line_start + max(0, statement.count("\n"))
        chunk_index = len(chunks)
        chunks.append(
            _chunk(
                statement,
                title=f"{relative_path}::{name}",
                relative_path=relative_path,
                language=language,
                symbol_kind=symbol_kind,
                primary_symbol=name,
                relationship=relationship,
                line_start=line_start,
                line_end=line_end,
                chunk_index=chunk_index,
            )
        )
        if match:
            symbols.append(_symbol(name, name, symbol_kind, language, relative_path, line_start, line_end, chunk_index))
    return _result(chunks, symbols, (), language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _parse_javascript_like(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    chunks: list[CodeChunk] = []
    symbols: list[CodeSymbol] = []
    references: list[CodeReference] = []
    lines = raw_text.splitlines()
    module_chunk = _chunk(
        raw_text,
        title=f"{relative_path}::module",
        relative_path=relative_path,
        language=language,
        symbol_kind="module",
        primary_symbol="module",
        relationship="definition",
        line_start=1,
        line_end=max(1, len(lines)),
        chunk_index=0,
    )
    chunks.append(module_chunk)
    for match in JS_SYMBOL_RE.finditer(raw_text):
        name = match.group("name") or match.group("var")
        symbol_kind = "class" if match.group("kind") == "class" else "function"
        line_start = raw_text[: match.start()].count("\n") + 1
        line_end = min(len(lines), line_start + 20)
        chunk_index = len(chunks)
        routes = [route.group("route") for route in ROUTE_RE.finditer(raw_text[max(0, match.start() - 160) : match.end() + 240])]
        chunk_relationship = "route" if routes else "definition"
        chunks.append(
            _chunk_from_lines(
                lines,
                title=f"{relative_path}::{name}",
                relative_path=relative_path,
                language=language,
                symbol_kind=symbol_kind,
                primary_symbol=name,
                relationship=chunk_relationship,
                line_start=line_start,
                line_end=line_end,
                chunk_index=chunk_index,
                extra={"routes": routes} if routes else None,
            )
        )
        symbols.append(
            _symbol(
                name,
                name,
                symbol_kind,
                language,
                relative_path,
                line_start,
                line_end,
                chunk_index,
                exported=not name.startswith("_"),
                metadata={"routes": routes} if routes else None,
            )
        )
        references.extend(_javascript_call_references(raw_text, match=match, symbol_name=name, language=language, relative_path=relative_path, chunk_index=chunk_index))
    for route in ROUTE_RE.finditer(raw_text):
        references.append(
            CodeReference(
                relationship_kind="route",
                target=route.group("route"),
                language=language,
                path=relative_path,
                line_start=raw_text[: route.start()].count("\n") + 1,
                line_end=raw_text[: route.start()].count("\n") + 1,
                chunk_index=0,
                source_symbol=route.group("handler"),
                metadata={"method": route.group("method").upper()},
            )
        )
    return _result(chunks, symbols, references, language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _parse_csharp(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    lines = raw_text.splitlines()
    line_offsets = _line_offsets(raw_text)
    chunks: list[CodeChunk] = [
        _chunk(
            raw_text,
            title=f"{relative_path}::module",
            relative_path=relative_path,
            language=language,
            symbol_kind="module",
            primary_symbol="module",
            relationship="definition",
            line_start=1,
            line_end=max(1, len(lines)),
            chunk_index=0,
        )
    ]
    symbols: list[CodeSymbol] = []
    references: list[CodeReference] = []

    namespace_match = CS_NAMESPACE_RE.search(raw_text)
    namespace_name = namespace_match.group("name") if namespace_match else ""
    if namespace_match:
        namespace_line = _line_for_offset(line_offsets, namespace_match.start())
        symbols.append(
            _symbol(
                namespace_name,
                namespace_name,
                "namespace",
                language,
                relative_path,
                namespace_line,
                namespace_line,
                0,
                exported=True,
            )
        )

    for using in CS_USING_RE.finditer(raw_text):
        line = _line_for_offset(line_offsets, using.start())
        references.append(
            CodeReference(
                relationship_kind="using",
                target=using.group("target"),
                language=language,
                path=relative_path,
                line_start=line,
                line_end=line,
                chunk_index=0,
                confidence=0.95,
            )
        )

    class_infos: list[dict[str, Any]] = []
    for match in CS_TYPE_RE.finditer(raw_text):
        name = match.group("name")
        kind = match.group("kind").lower()
        line_start = _line_for_offset(line_offsets, match.start())
        line_end = _csharp_symbol_line_end(lines, line_start)
        qualified = f"{namespace_name}.{name}" if namespace_name else name
        attrs = _csharp_attributes_before(lines, line_start)
        route_prefixes = _csharp_routes_from_attrs(attrs, class_route=True)
        chunk_index = len(chunks)
        chunks.append(
            _chunk_from_lines(
                lines,
                title=f"{relative_path}::{qualified}",
                relative_path=relative_path,
                language=language,
                symbol_kind=kind,
                primary_symbol=qualified,
                relationship="definition",
                line_start=line_start,
                line_end=line_end,
                chunk_index=chunk_index,
                extra={"routes": route_prefixes} if route_prefixes else None,
            )
        )
        symbols.append(
            _symbol(
                name,
                qualified,
                kind,
                language,
                relative_path,
                line_start,
                line_end,
                chunk_index,
                parent_symbol=namespace_name or None,
                exported=_common_symbol_exported(raw_text, match.start(), name),
                metadata={"routes": route_prefixes} if route_prefixes else None,
            )
        )
        class_infos.append(
            {
                "name": name,
                "qualified": qualified,
                "line_start": line_start,
                "line_end": line_end,
                "routes": route_prefixes,
            }
        )

    for match in CS_METHOD_RE.finditer(raw_text):
        name = match.group("name")
        if name in {"if", "for", "foreach", "while", "switch", "catch"}:
            continue
        line_start = _line_for_offset(line_offsets, match.start())
        parent = _csharp_parent_class(class_infos, line_start)
        attrs = _csharp_attributes_before(lines, line_start)
        symbol_kind = "test" if CS_TEST_ATTR_RE.search("\n".join(attrs)) else "method"
        qualified = f"{parent['qualified']}.{name}" if parent else f"{namespace_name}.{name}" if namespace_name else name
        routes = _combine_csharp_routes(parent.get("routes", []) if parent else [], _csharp_routes_from_attrs(attrs, class_route=False))
        line_end = _csharp_symbol_line_end(lines, line_start)
        chunk_index = len(chunks)
        chunks.append(
            _chunk_from_lines(
                lines,
                title=f"{relative_path}::{qualified}",
                relative_path=relative_path,
                language=language,
                symbol_kind=symbol_kind,
                primary_symbol=qualified,
                relationship="route" if routes else "test" if symbol_kind == "test" else "definition",
                line_start=line_start,
                line_end=line_end,
                chunk_index=chunk_index,
                extra={"routes": routes} if routes else None,
            )
        )
        symbols.append(
            _symbol(
                name,
                qualified,
                symbol_kind,
                language,
                relative_path,
                line_start,
                line_end,
                chunk_index,
                parent_symbol=parent["qualified"] if parent else namespace_name or None,
                exported=_common_symbol_exported(raw_text, match.start(), name),
                metadata={"routes": routes} if routes else None,
            )
        )
        for route in routes:
            references.append(
                CodeReference(
                    relationship_kind="route",
                    target=route,
                    language=language,
                    path=relative_path,
                    line_start=line_start,
                    line_end=line_start,
                    chunk_index=chunk_index,
                    source_symbol=qualified,
                    confidence=0.95,
                    metadata={"framework": "aspnet"},
                )
            )
        method_body = "\n".join(lines[max(0, line_start - 1) : max(line_start, line_end)])
        for call in CS_CALL_RE.finditer(method_body):
            target = call.group("target")
            if target == name or target in CS_CALL_SKIP or target == match.group("return_type"):
                continue
            references.append(
                CodeReference(
                    relationship_kind="call",
                    target=target,
                    language=language,
                    path=relative_path,
                    line_start=line_start + method_body[: call.start()].count("\n"),
                    line_end=line_start + method_body[: call.start()].count("\n"),
                    chunk_index=chunk_index,
                    source_symbol=qualified,
                    confidence=0.7,
                )
            )

    if not symbols:
        return _fallback_result(raw_text, relative_path=relative_path, language=language)
    return _result(chunks, symbols, references, language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _parse_frontend_markup(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    lines = raw_text.splitlines()
    component_name = _frontend_component_name(raw_text, relative_path, language)
    chunks = [
        _chunk(
            raw_text,
            title=f"{relative_path}::{component_name}",
            relative_path=relative_path,
            language=language,
            symbol_kind="component",
            primary_symbol=component_name,
            relationship="definition",
            line_start=1,
            line_end=max(1, len(lines)),
            chunk_index=0,
        )
    ]
    symbols = [
        _symbol(
            component_name,
            component_name,
            "component",
            language,
            relative_path,
            1,
            max(1, len(lines)),
            0,
            exported=True,
        )
    ]
    references: list[CodeReference] = []
    for pattern, relationship, target_group in (
        (FRONTEND_IMPORT_RE, "import", "target"),
        (FRONTEND_COMPONENT_TAG_RE, "component", "name"),
        (FRONTEND_ACTION_RE, "form_action", "target"),
    ):
        for match in pattern.finditer(raw_text):
            references.append(
                CodeReference(
                    relationship_kind=relationship,
                    target=match.group(target_group),
                    language=language,
                    path=relative_path,
                    line_start=raw_text[: match.start()].count("\n") + 1,
                    line_end=raw_text[: match.start()].count("\n") + 1,
                    chunk_index=0,
                    source_symbol=component_name,
                )
            )
    for match in FRONTEND_EVENT_RE.finditer(raw_text):
        references.append(
            CodeReference(
                relationship_kind="event",
                target=match.group("handler"),
                language=language,
                path=relative_path,
                line_start=raw_text[: match.start()].count("\n") + 1,
                line_end=raw_text[: match.start()].count("\n") + 1,
                chunk_index=0,
                source_symbol=component_name,
                metadata={"event": match.group("event")},
            )
        )
    references.extend(_html_selector_references(raw_text, language=language, relative_path=relative_path, source_symbol=component_name))
    return _result(chunks, symbols, references, language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _parse_stylesheet(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    lines = raw_text.splitlines()
    chunk = _chunk(
        raw_text,
        title=f"{relative_path}::stylesheet",
        relative_path=relative_path,
        language=language,
        symbol_kind="stylesheet",
        primary_symbol=Path(relative_path).name,
        relationship="definition",
        line_start=1,
        line_end=max(1, len(lines)),
        chunk_index=0,
    )
    symbols: list[CodeSymbol] = []
    references: list[CodeReference] = []
    seen_symbols: set[tuple[str, str]] = set()
    for pattern, symbol_kind, prefix in (
        (CSS_CLASS_RE, "selector", "."),
        (CSS_ID_RE, "selector", "#"),
        (CSS_CUSTOM_PROPERTY_RE, "custom_property", ""),
        (CSS_KEYFRAMES_RE, "keyframes", ""),
    ):
        for match in pattern.finditer(raw_text):
            name = f"{prefix}{match.group('name')}"
            key = (symbol_kind, name)
            if key in seen_symbols:
                continue
            seen_symbols.add(key)
            line = raw_text[: match.start()].count("\n") + 1
            symbols.append(_symbol(name, name, symbol_kind, language, relative_path, line, line, 0, exported=True))
    for media in CSS_MEDIA_RE.finditer(raw_text):
        line = raw_text[: media.start()].count("\n") + 1
        references.append(
            CodeReference(
                relationship_kind="media_query",
                target=media.group("query").strip(),
                language=language,
                path=relative_path,
                line_start=line,
                line_end=line,
                chunk_index=0,
                source_symbol=Path(relative_path).name,
            )
        )
    return _result([chunk], symbols, references, language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _parse_common_language(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    lines = raw_text.splitlines()
    line_offsets = _line_offsets(raw_text)
    chunks: list[CodeChunk] = []
    symbols: list[CodeSymbol] = []
    for symbol_kind, group_name, pattern in COMMON_LANGUAGE_SYMBOL_PATTERNS[language]:
        for match in pattern.finditer(raw_text):
            name = match.group(group_name)
            line_start = _line_for_offset(line_offsets, match.start())
            line_end = _common_symbol_line_end(lines, line_start)
            chunk_index = len(chunks)
            chunks.append(
                _chunk_from_lines(
                    lines,
                    title=f"{relative_path}::{name}",
                    relative_path=relative_path,
                    language=language,
                    symbol_kind=symbol_kind,
                    primary_symbol=name,
                    relationship="definition",
                    line_start=line_start,
                    line_end=line_end,
                    chunk_index=chunk_index,
                )
            )
            symbols.append(_symbol(name, name, symbol_kind, language, relative_path, line_start, line_end, chunk_index, exported=_common_symbol_exported(raw_text, match.start(), name)))
    if not chunks:
        return _fallback_result(raw_text, relative_path=relative_path, language=language)
    return _result(chunks, symbols, (), language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _parse_notebook(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    try:
        payload = json.loads(raw_text)
    except json.JSONDecodeError as exc:
        return _fallback_result(
            raw_text,
            relative_path=relative_path,
            language=language,
            diagnostics={"error_type": type(exc).__name__, "line": exc.lineno},
        )
    cells = payload.get("cells") if isinstance(payload, dict) else None
    if not isinstance(cells, list):
        return _fallback_result(
            raw_text,
            relative_path=relative_path,
            language=language,
            diagnostics={"error_type": "InvalidNotebook", "reason": "missing cells"},
        )
    chunks: list[CodeChunk] = []
    symbols: list[CodeSymbol] = []
    line_cursor = 1
    for index, cell in enumerate(cells):
        if not isinstance(cell, dict):
            continue
        source = cell.get("source", "")
        text = "".join(source) if isinstance(source, list) else str(source or "")
        cell_type = str(cell.get("cell_type") or "cell")
        line_count = max(1, len(text.splitlines()))
        primary_symbol = f"{cell_type}_cell_{index}"
        chunk_index = len(chunks)
        chunks.append(
            _chunk(
                text,
                title=f"{relative_path}::{primary_symbol}",
                relative_path=relative_path,
                language=language,
                symbol_kind="notebook_cell",
                primary_symbol=primary_symbol,
                relationship="definition",
                line_start=line_cursor,
                line_end=line_cursor + line_count - 1,
                chunk_index=chunk_index,
                extra={"cell_type": cell_type, "cell_index": index},
            )
        )
        symbols.append(
            _symbol(
                primary_symbol,
                primary_symbol,
                "notebook_cell",
                language,
                relative_path,
                line_cursor,
                line_cursor + line_count - 1,
                chunk_index,
                metadata={"cell_type": cell_type, "cell_index": index},
            )
        )
        line_cursor += line_count
    return _result(chunks, symbols, (), language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _parse_config_like(raw_text: str, *, relative_path: str, language: str) -> CodeIndexResult:
    lines = raw_text.splitlines()
    chunk = _chunk(
        raw_text,
        title=f"{relative_path}::config",
        relative_path=relative_path,
        language=language,
        symbol_kind="config",
        primary_symbol=Path(relative_path).name,
        relationship="config",
        line_start=1,
        line_end=max(1, len(lines)),
        chunk_index=0,
    )
    symbol = _symbol(
        Path(relative_path).name,
        Path(relative_path).name,
        "config",
        language,
        relative_path,
        1,
        max(1, len(lines)),
        0,
    )
    return _result([chunk], [symbol], (), language=language, parser_status="parsed", generated=_is_generated_file(raw_text))


def _fallback_result(
    raw_text: str,
    *,
    relative_path: str,
    language: str,
    diagnostics: dict[str, Any] | None = None,
) -> CodeIndexResult:
    chunk = _chunk(
        raw_text,
        title=f"{relative_path}::fallback",
        relative_path=relative_path,
        language=language,
        symbol_kind="fallback",
        primary_symbol=Path(relative_path).name,
        relationship="fallback",
        line_start=1,
        line_end=max(1, len(raw_text.splitlines())),
        chunk_index=0,
        parser_status="fallback",
    )
    metadata: dict[str, Any] = {
        "language": language,
        "parser_status": "fallback",
        "symbol_count": 0,
        "reference_count": 0,
    }
    generated = _is_generated_file(raw_text)
    if generated:
        metadata["generated"] = True
    if diagnostics:
        metadata["parser_diagnostics"] = diagnostics
    return CodeIndexResult(chunks=_mark_generated_chunks((chunk,), generated=generated), metadata=metadata)


def _is_migration_path(relative_path: str) -> bool:
    normalized = relative_path.replace("\\", "/").lower()
    return "/migrations/" in f"/{normalized}" or "migration" in Path(normalized).name


def _csharp_attributes_before(lines: list[str], line_start: int) -> list[str]:
    attrs: list[str] = []
    index = max(0, line_start - 2)
    while index >= 0:
        stripped = lines[index].strip()
        if not stripped:
            index -= 1
            continue
        if stripped.startswith("["):
            attrs.insert(0, stripped)
            index -= 1
            continue
        break
    return attrs


def _csharp_routes_from_attrs(attrs: list[str], *, class_route: bool) -> list[str]:
    routes: list[str] = []
    for attr in attrs:
        for match in CS_ROUTE_ATTR_RE.finditer(attr):
            attr_name = match.group("attr").lower()
            route = str(match.group("route") or "").strip("/")
            if class_route and attr_name == "route" and route:
                routes.append(route)
            elif not class_route and attr_name.startswith("http"):
                routes.append(route)
    return routes


def _combine_csharp_routes(prefixes: list[str], routes: list[str]) -> list[str]:
    if not routes:
        return []
    if not prefixes:
        return [route.strip("/") for route in routes]
    combined: list[str] = []
    for prefix in prefixes:
        for route in routes:
            combined.append("/".join(part.strip("/") for part in (prefix, route) if part.strip("/")))
    return combined


def _csharp_parent_class(class_infos: list[dict[str, Any]], line_start: int) -> dict[str, Any] | None:
    candidates = [item for item in class_infos if int(item["line_start"]) <= line_start <= int(item["line_end"])]
    if candidates:
        return sorted(candidates, key=lambda item: int(item["line_start"]), reverse=True)[0]
    previous = [item for item in class_infos if int(item["line_start"]) <= line_start]
    return sorted(previous, key=lambda item: int(item["line_start"]), reverse=True)[0] if previous else None


def _csharp_symbol_line_end(lines: list[str], line_start: int) -> int:
    if not lines:
        return 1
    balance = 0
    seen_open = False
    for index in range(max(0, line_start - 1), len(lines)):
        line = lines[index]
        balance += line.count("{")
        if "{" in line:
            seen_open = True
        balance -= line.count("}")
        if seen_open and balance <= 0:
            return index + 1
    return min(len(lines), max(line_start, line_start + 20))


def _frontend_component_name(raw_text: str, relative_path: str, language: str) -> str:
    if language == "vue":
        match = re.search(r"\bname\s*:\s*['\"](?P<name>[A-Za-z_][A-Za-z0-9_]*)['\"]", raw_text)
        if match:
            return match.group("name")
    return Path(relative_path).stem.replace(".module", "")


def _html_selector_references(raw_text: str, *, language: str, relative_path: str, source_symbol: str) -> list[CodeReference]:
    references: list[CodeReference] = []
    seen: set[str] = set()
    for match in HTML_CLASS_RE.finditer(raw_text):
        for value in str(match.group("value") or "").split():
            target = f".{value}"
            if target in seen:
                continue
            seen.add(target)
            references.append(
                CodeReference(
                    relationship_kind="selector",
                    target=target,
                    language=language,
                    path=relative_path,
                    line_start=raw_text[: match.start()].count("\n") + 1,
                    line_end=raw_text[: match.start()].count("\n") + 1,
                    chunk_index=0,
                    source_symbol=source_symbol,
                )
            )
    for match in HTML_ID_RE.finditer(raw_text):
        target = f"#{match.group('value')}"
        if target in seen:
            continue
        seen.add(target)
        references.append(
            CodeReference(
                relationship_kind="selector",
                target=target,
                language=language,
                path=relative_path,
                line_start=raw_text[: match.start()].count("\n") + 1,
                line_end=raw_text[: match.start()].count("\n") + 1,
                chunk_index=0,
                source_symbol=source_symbol,
            )
        )
    return references


def _result(
    chunks: list[CodeChunk],
    symbols: list[CodeSymbol] | tuple[CodeSymbol, ...],
    references: list[CodeReference] | tuple[CodeReference, ...],
    *,
    language: str,
    parser_status: str,
    generated: bool = False,
) -> CodeIndexResult:
    metadata: dict[str, Any] = {
        "language": language,
        "parser_status": parser_status,
        "symbol_count": len(symbols),
        "reference_count": len(references),
    }
    if generated:
        metadata["generated"] = True
    return CodeIndexResult(
        chunks=_mark_generated_chunks(tuple(chunks), generated=generated),
        symbols=_mark_generated_symbols(tuple(symbols), generated=generated),
        references=_mark_generated_references(tuple(references), generated=generated),
        metadata=metadata,
    )


def _chunk_from_lines(
    lines: list[str],
    *,
    title: str,
    relative_path: str,
    language: str,
    symbol_kind: str,
    primary_symbol: str,
    relationship: str,
    line_start: int,
    line_end: int,
    chunk_index: int,
    extra: dict[str, Any] | None = None,
) -> CodeChunk:
    body = "\n".join(lines[max(0, line_start - 1) : max(line_start, line_end)])
    return _chunk(
        body,
        title=title,
        relative_path=relative_path,
        language=language,
        symbol_kind=symbol_kind,
        primary_symbol=primary_symbol,
        relationship=relationship,
        line_start=line_start,
        line_end=line_end,
        chunk_index=chunk_index,
        extra=extra,
    )


def _chunk(
    text: str,
    *,
    title: str,
    relative_path: str,
    language: str,
    symbol_kind: str,
    primary_symbol: str,
    relationship: str,
    line_start: int,
    line_end: int,
    chunk_index: int,
    parser_status: str = "parsed",
    extra: dict[str, Any] | None = None,
) -> CodeChunk:
    redacted, _ = redact_text(text)
    redacted = EMAIL_RE.sub("[REDACTED:email]", redacted)
    metadata: dict[str, Any] = {
        "code": {
            "language": language,
            "primary_symbol": primary_symbol,
            "symbol_kind": symbol_kind,
            "relationship": relationship,
            "range": {"line_start": int(line_start), "line_end": int(line_end)},
            "parser_status": parser_status,
            "source_path": relative_path,
        },
        "language": language,
        "symbol_kind": symbol_kind,
        "relationship": relationship,
        "parser_status": parser_status,
    }
    if extra:
        metadata["code"].update(extra)
        metadata.update(extra)
    return CodeChunk(
        chunk_index=chunk_index,
        title=title,
        body=redacted.strip(),
        locator=f"line:{line_start}-{line_end}",
        token_estimate=max(1, len(redacted.split())),
        metadata=metadata,
    )


def _is_generated_file(raw_text: str) -> bool:
    head = "\n".join(raw_text.splitlines()[:20])
    return bool(GENERATED_MARKER_RE.search(head))


def _mark_generated_chunks(chunks: tuple[CodeChunk, ...], *, generated: bool) -> tuple[CodeChunk, ...]:
    if not generated:
        return chunks
    marked: list[CodeChunk] = []
    for chunk in chunks:
        code = dict(chunk.metadata.get("code") or {})
        code["generated"] = True
        marked.append(replace(chunk, metadata={**chunk.metadata, "generated": True, "code": code}))
    return tuple(marked)


def _mark_generated_symbols(symbols: tuple[CodeSymbol, ...], *, generated: bool) -> tuple[CodeSymbol, ...]:
    if not generated:
        return symbols
    return tuple(replace(symbol, metadata={**symbol.metadata, "generated": True}) for symbol in symbols)


def _mark_generated_references(references: tuple[CodeReference, ...], *, generated: bool) -> tuple[CodeReference, ...]:
    if not generated:
        return references
    return tuple(replace(reference, metadata={**reference.metadata, "generated": True}) for reference in references)


def _symbol(
    name: str,
    qualified_name: str,
    symbol_kind: str,
    language: str,
    relative_path: str,
    line_start: int,
    line_end: int,
    chunk_index: int,
    *,
    parent_symbol: str | None = None,
    exported: bool | None = None,
    signature: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> CodeSymbol:
    return CodeSymbol(
        name=name,
        qualified_name=qualified_name,
        symbol_kind=symbol_kind,
        language=language,
        path=relative_path,
        line_start=int(line_start),
        line_end=int(line_end),
        chunk_index=int(chunk_index),
        parent_symbol=parent_symbol,
        exported=exported,
        signature=signature,
        metadata=metadata or {},
    )


def _symbol_metadata(symbol: CodeSymbol) -> dict[str, Any]:
    data = {
        "name": symbol.name,
        "qualified_name": symbol.qualified_name,
        "symbol_kind": symbol.symbol_kind,
        "language": symbol.language,
        "path": symbol.path,
        "line_start": symbol.line_start,
        "line_end": symbol.line_end,
        "chunk_index": symbol.chunk_index,
        "parent_symbol": symbol.parent_symbol,
        "exported": symbol.exported,
        "signature": symbol.signature,
        "parser_status": symbol.parser_status,
        "confidence": symbol.confidence,
        "metadata": symbol.metadata,
    }
    return {key: value for key, value in data.items() if value is not None}


def _reference_metadata(reference: CodeReference) -> dict[str, Any]:
    data = {
        "relationship_kind": reference.relationship_kind,
        "target": reference.target,
        "language": reference.language,
        "path": reference.path,
        "line_start": reference.line_start,
        "line_end": reference.line_end,
        "chunk_index": reference.chunk_index,
        "source_symbol": reference.source_symbol,
        "parser_status": reference.parser_status,
        "confidence": reference.confidence,
        "metadata": reference.metadata,
    }
    return {key: value for key, value in data.items() if value is not None}


def _python_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    names = [arg.arg for arg in node.args.posonlyargs + node.args.args + node.args.kwonlyargs]
    if node.args.vararg:
        names.append(f"*{node.args.vararg.arg}")
    if node.args.kwarg:
        names.append(f"**{node.args.kwarg.arg}")
    return f"{node.name}({', '.join(names)})"


def _python_routes(node: ast.FunctionDef | ast.AsyncFunctionDef) -> list[str]:
    routes: list[str] = []
    for decorator in node.decorator_list:
        if not isinstance(decorator, ast.Call):
            continue
        func = decorator.func
        if not isinstance(func, ast.Attribute) or func.attr not in {"get", "post", "put", "patch", "delete"}:
            continue
        if decorator.args and isinstance(decorator.args[0], ast.Constant) and isinstance(decorator.args[0].value, str):
            routes.append(decorator.args[0].value)
    return routes


def _python_function_symbol_kind(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    if _has_pytest_fixture_decorator(node):
        return "fixture"
    if node.name.startswith("test_"):
        return "test"
    return "function"


def _python_class_metadata(node: ast.ClassDef) -> dict[str, Any]:
    metadata: dict[str, Any] = {}
    bases = [_python_target_name(base) for base in node.bases]
    decorators = [_python_target_name(decorator.func if isinstance(decorator, ast.Call) else decorator) for decorator in node.decorator_list]
    bases = [base for base in bases if base]
    decorators = [decorator for decorator in decorators if decorator]
    if bases:
        metadata["bases"] = bases
    if decorators:
        metadata["decorators"] = decorators
    return metadata


def _python_class_references(
    node: ast.ClassDef,
    *,
    language: str,
    relative_path: str,
    chunk_index: int,
    source_symbol: str,
) -> list[CodeReference]:
    references: list[CodeReference] = []
    for base in node.bases:
        target = _python_target_name(base)
        if target:
            references.append(
                CodeReference(
                    relationship_kind="inherits",
                    target=target,
                    language=language,
                    path=relative_path,
                    line_start=getattr(base, "lineno", node.lineno),
                    line_end=getattr(base, "end_lineno", getattr(base, "lineno", node.lineno)),
                    chunk_index=chunk_index,
                    source_symbol=source_symbol,
                    confidence=1.0,
                )
            )
    for decorator in node.decorator_list:
        target = _python_target_name(decorator.func if isinstance(decorator, ast.Call) else decorator)
        if target:
            references.append(
                CodeReference(
                    relationship_kind="decorator",
                    target=target,
                    language=language,
                    path=relative_path,
                    line_start=getattr(decorator, "lineno", node.lineno),
                    line_end=getattr(decorator, "end_lineno", getattr(decorator, "lineno", node.lineno)),
                    chunk_index=chunk_index,
                    source_symbol=source_symbol,
                    confidence=1.0,
                )
            )
    return _dedupe_references(references)


def _has_pytest_fixture_decorator(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    for decorator in node.decorator_list:
        func = decorator.func if isinstance(decorator, ast.Call) else decorator
        if isinstance(func, ast.Name) and func.id == "fixture":
            return True
        if isinstance(func, ast.Attribute) and func.attr == "fixture":
            return True
    return False


def _python_references(
    node: ast.AST,
    *,
    language: str,
    relative_path: str,
    chunk_index: int,
    source_symbol: str | None,
    source_kind: str | None = None,
) -> list[CodeReference]:
    references: list[CodeReference] = []
    for child in ast.walk(node):
        if isinstance(child, ast.ImportFrom):
            module = child.module or ""
            for alias in child.names:
                target = f"{module}.{alias.name}" if module else alias.name
                references.append(
                    CodeReference(
                        relationship_kind="import",
                        target=target,
                        language=language,
                        path=relative_path,
                        line_start=child.lineno,
                        line_end=child.lineno,
                        chunk_index=chunk_index,
                        source_symbol=source_symbol,
                        confidence=1.0,
                    )
                )
        elif isinstance(child, ast.Import):
            for alias in child.names:
                references.append(
                    CodeReference(
                        relationship_kind="import",
                        target=alias.name,
                        language=language,
                        path=relative_path,
                        line_start=child.lineno,
                        line_end=child.lineno,
                        chunk_index=chunk_index,
                        source_symbol=source_symbol,
                        confidence=1.0,
                    )
                )
        elif isinstance(child, ast.Call):
            target = _call_target(child.func)
            if target:
                references.append(
                    CodeReference(
                        relationship_kind="test" if source_kind == "test" else "call",
                        target=target,
                        language=language,
                        path=relative_path,
                        line_start=getattr(child, "lineno", 1),
                        line_end=getattr(child, "end_lineno", getattr(child, "lineno", 1)),
                        chunk_index=chunk_index,
                        source_symbol=source_symbol,
                    )
                )
    return _dedupe_references(references)


def _python_target_name(node: ast.AST) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        base = _python_target_name(node.value)
        return f"{base}.{node.attr}" if base else node.attr
    if isinstance(node, ast.Call):
        return _python_target_name(node.func)
    if isinstance(node, ast.Subscript):
        return _python_target_name(node.value)
    return None


def _python_fixture_references(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    *,
    language: str,
    relative_path: str,
    chunk_index: int,
) -> list[CodeReference]:
    return [
        CodeReference(
            relationship_kind="fixture",
            target=arg.arg,
            language=language,
            path=relative_path,
            line_start=node.lineno,
            line_end=getattr(node, "end_lineno", node.lineno),
            chunk_index=chunk_index,
            source_symbol=node.name,
            confidence=1.0,
        )
        for arg in node.args.args
        if arg.arg != "self"
    ]


def _javascript_call_references(
    raw_text: str,
    *,
    match: re.Match[str],
    symbol_name: str,
    language: str,
    relative_path: str,
    chunk_index: int,
) -> list[CodeReference]:
    snippet = raw_text[match.end() : match.end() + 500]
    references: list[CodeReference] = []
    for call in JS_CALL_RE.finditer(snippet):
        target = call.group("target")
        if target == symbol_name or target in JS_CALL_SKIP:
            continue
        offset = match.end() + call.start()
        line = raw_text[:offset].count("\n") + 1
        references.append(
            CodeReference(
                relationship_kind="call",
                target=target,
                language=language,
                path=relative_path,
                line_start=line,
                line_end=line,
                chunk_index=chunk_index,
                source_symbol=symbol_name,
            )
        )
    return _dedupe_references(references)


def _common_symbol_line_end(lines: list[str], line_start: int) -> int:
    if not lines:
        return 1
    return min(len(lines), max(line_start, line_start + 20))


def _common_symbol_exported(raw_text: str, start: int, name: str) -> bool | None:
    prefix = raw_text[max(0, start - 32) : start].lower()
    return bool("pub " in prefix or "public " in prefix or "export " in prefix or name[:1].isupper())


def _call_target(func: ast.AST) -> str | None:
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        base = _call_target(func.value)
        return f"{base}.{func.attr}" if base else func.attr
    return None


def _dedupe_references(references: list[CodeReference]) -> list[CodeReference]:
    seen: set[tuple[str, str, int, str | None]] = set()
    result: list[CodeReference] = []
    for reference in references:
        key = (reference.relationship_kind, reference.target, reference.line_start, reference.source_symbol)
        if key in seen:
            continue
        seen.add(key)
        result.append(reference)
    return result


def _line_offsets(text: str) -> list[int]:
    offsets = [0]
    for match in re.finditer("\n", text):
        offsets.append(match.end())
    return offsets


def _line_for_offset(offsets: list[int], offset: int) -> int:
    line = 1
    for index, value in enumerate(offsets, start=1):
        if value > offset:
            break
        line = index
    return line


def _relative_path(path: Path, root: Path) -> str:
    try:
        resolved = path.resolve()
        return resolved.relative_to(root).as_posix()
    except (OSError, ValueError):
        return path.name


def _normalise_relative_path(path: str) -> str:
    normalised = str(path).replace("\\", "/").strip("/")
    return normalised or Path(path).name


def scope_hash(root_name: str | None, path: str) -> str:
    return hashlib.sha256(f"{root_name or ''}:{path}".encode("utf-8")).hexdigest()[:16]
