from __future__ import annotations

from dataclasses import dataclass
import ipaddress
from typing import Any, Callable
from urllib.parse import urlparse

from .database import DEFAULT_DATABASE_URL
from .reranking import (
    DEFAULT_MAX_RERANK_PASSAGE_TOKENS,
    DEFAULT_RERANK_MICROBATCH_SIZE,
    DEFAULT_RERANK_TOP_N,
    DEFAULT_RERANKER_AWQ_MODEL,
    DEFAULT_RERANKER_MODEL,
    DEFAULT_RERANKER_QUANTIZATION,
    normalize_reranker_quantization,
)
from .search_index import DEFAULT_VESPA_BASE_URL, SNOWFLAKE_EMBEDDING_DIMENSIONS, SNOWFLAKE_EMBEDDING_MODEL


APPLY_LIVE = "live"
APPLY_RELOAD = "reload"
APPLY_RESTART_COMPONENT = "restart_component"
APPLY_REINDEX_REQUIRED = "reindex_required"
APPLY_MANUAL_PROCESS_RESTART = "manual_process_restart"

DEFAULT_CRAWLER_GLOBAL_EXCLUDE_GLOBS = [
    "private/**",
    "node_modules/**",
    ".git/**",
    ".worktrees/**",
    "**/.vs/**",
    "**/CopilotIndices/**",
    "**/*.db",
    "**/*.db-wal",
    "**/*.db-shm",
    "**/*.sqlite",
    "**/*.sqlite-*",
    "desktop.ini",
]


@dataclass(frozen=True)
class SettingDefinition:
    key: str
    category: str
    default: Any
    value_type: str
    description: str
    env_var: str | None = None
    sensitive: bool = False
    read_only: bool = False
    apply_mode: str = APPLY_LIVE
    affected_components: tuple[str, ...] = ()
    validator: Callable[[Any], Any] | None = None

    def validate(self, value: Any) -> Any:
        parsed = _coerce(value, self.value_type)
        if self.validator:
            parsed = self.validator(parsed)
        return parsed


def get_definition(key: str) -> SettingDefinition:
    try:
        return _REGISTRY_BY_KEY[key]
    except KeyError as exc:
        raise KeyError(f"unknown setting: {key}") from exc


def public_definitions() -> list[SettingDefinition]:
    return sorted(SETTING_REGISTRY, key=lambda item: item.key)


def _coerce(value: Any, value_type: str) -> Any:
    if value_type == "str":
        return str(value)
    if value_type == "int":
        return int(value)
    if value_type == "float":
        return float(value)
    if value_type == "bool":
        if isinstance(value, bool):
            return value
        lowered = str(value).strip().lower()
        if lowered in {"1", "true", "yes", "on"}:
            return True
        if lowered in {"0", "false", "no", "off"}:
            return False
        raise ValueError(f"invalid boolean value: {value}")
    if value_type == "list[str]":
        if isinstance(value, (list, tuple)):
            return [str(item) for item in value]
        return [item.strip() for item in str(value).split(",") if item.strip()]
    return value


def _min_int(minimum: int) -> Callable[[Any], Any]:
    def validate(value: Any) -> int:
        parsed = int(value)
        if parsed < minimum:
            raise ValueError(f"value must be >= {minimum}")
        return parsed

    return validate


def _range_int(minimum: int, maximum: int) -> Callable[[Any], Any]:
    def validate(value: Any) -> int:
        parsed = int(value)
        if parsed < minimum or parsed > maximum:
            raise ValueError(f"value must be between {minimum} and {maximum}")
        return parsed

    return validate


def _range_float(minimum: float, maximum: float) -> Callable[[Any], Any]:
    def validate(value: Any) -> float:
        parsed = float(value)
        if parsed < minimum or parsed > maximum:
            raise ValueError(f"value must be between {minimum} and {maximum}")
        return parsed

    return validate


def _choice(*choices: str) -> Callable[[Any], Any]:
    def validate(value: Any) -> str:
        parsed = str(value)
        if parsed not in choices:
            raise ValueError(f"value must be one of: {', '.join(choices)}")
        return parsed

    return validate


def _reranker_quantization(value: Any) -> str:
    return normalize_reranker_quantization(value)


def _loopback_http_url(value: Any) -> str:
    parsed_value = str(value).strip()
    parsed = urlparse(parsed_value)
    if parsed.scheme not in {"http", "https"}:
        raise ValueError("value must use http or https")
    hostname = parsed.hostname
    if not hostname:
        raise ValueError("value must include a host")
    if hostname.lower() in {"localhost", "host.docker.internal", "ollama", "asr"}:
        return parsed_value.rstrip("/")
    try:
        if ipaddress.ip_address(hostname).is_loopback:
            return parsed_value.rstrip("/")
    except ValueError:
        pass
    raise ValueError("value must use a local loopback host, Docker host gateway, or a Docker Compose local model service")


def _optional_loopback_http_url(value: Any) -> str:
    parsed_value = str(value).strip()
    if not parsed_value:
        return ""
    return _loopback_http_url(parsed_value)


SETTING_REGISTRY: tuple[SettingDefinition, ...] = (
    SettingDefinition(
        key="database.url",
        category="bootstrap",
        default=DEFAULT_DATABASE_URL,
        value_type="str",
        description="Primary PostgreSQL connection string.",
        env_var="FLUX_KB_DATABASE_URL",
        sensitive=True,
        read_only=True,
        apply_mode=APPLY_MANUAL_PROCESS_RESTART,
        affected_components=("database", "api", "cli", "mcp"),
    ),
    SettingDefinition(
        key="database.test_url",
        category="bootstrap",
        default="",
        value_type="str",
        description="Optional PostgreSQL test database connection string.",
        env_var="FLUX_KB_TEST_DATABASE_URL",
        sensitive=True,
        read_only=True,
        apply_mode=APPLY_MANUAL_PROCESS_RESTART,
        affected_components=("tests",),
    ),
    SettingDefinition(
        key="api.host",
        category="bootstrap",
        default="127.0.0.1",
        value_type="str",
        description="REST API bind host.",
        env_var="FLUX_KB_API_HOST",
        read_only=True,
        apply_mode=APPLY_MANUAL_PROCESS_RESTART,
        affected_components=("api",),
    ),
    SettingDefinition(
        key="api.port",
        category="bootstrap",
        default=8765,
        value_type="int",
        description="REST API bind port.",
        env_var="FLUX_KB_API_PORT",
        read_only=True,
        apply_mode=APPLY_MANUAL_PROCESS_RESTART,
        affected_components=("api",),
        validator=_range_int(1, 65535),
    ),
    SettingDefinition(
        key="capture.enabled",
        category="capture",
        default=True,
        value_type="bool",
        description="Enable automatic capture paths when integrations call them.",
        env_var="FLUX_KB_CAPTURE_ENABLED",
        apply_mode=APPLY_RELOAD,
        affected_components=("hooks", "mail"),
    ),
    SettingDefinition(
        key="codex.hooks.enabled",
        category="codex",
        default=True,
        value_type="bool",
        description="Enable Flux Codex hook policy evaluation.",
        env_var="FLUX_KB_CODEX_HOOKS_ENABLED",
        apply_mode=APPLY_RELOAD,
        affected_components=("hooks", "dashboard"),
    ),
    SettingDefinition(
        key="codex.hooks.preflight_enabled",
        category="codex",
        default=True,
        value_type="bool",
        description="Automatically inject relevant Flux memory into non-trivial Codex prompts.",
        env_var="FLUX_KB_CODEX_HOOKS_PREFLIGHT_ENABLED",
        apply_mode=APPLY_RELOAD,
        affected_components=("hooks", "retrieval", "dashboard"),
    ),
    SettingDefinition(
        key="codex.hooks.capture_enabled",
        category="codex",
        default=True,
        value_type="bool",
        description="Automatically capture durable Codex turn summaries from Stop hook output.",
        env_var="FLUX_KB_CODEX_HOOKS_CAPTURE_ENABLED",
        apply_mode=APPLY_RELOAD,
        affected_components=("hooks", "capture", "dashboard"),
    ),
    SettingDefinition(
        key="codex.hooks.capture_guidance_enabled",
        category="codex",
        default=True,
        value_type="bool",
        description="Inject guidance that makes Codex final responses more useful for Flux capture.",
        env_var="FLUX_KB_CODEX_HOOKS_CAPTURE_GUIDANCE_ENABLED",
        apply_mode=APPLY_RELOAD,
        affected_components=("hooks", "dashboard"),
    ),
    SettingDefinition(
        key="codex.hooks.reference_indexing_enabled",
        category="codex",
        default=True,
        value_type="bool",
        description="Index safe web and monitored-file references from Codex Stop hook output.",
        env_var="FLUX_KB_CODEX_HOOKS_REFERENCE_INDEXING_ENABLED",
        apply_mode=APPLY_RELOAD,
        affected_components=("hooks", "capture", "crawler", "dashboard"),
    ),
    SettingDefinition(
        key="codex.hooks.reference_max_count",
        category="codex",
        default=5,
        value_type="int",
        description="Maximum references indexed from one Codex Stop hook payload.",
        env_var="FLUX_KB_CODEX_HOOKS_REFERENCE_MAX_COUNT",
        apply_mode=APPLY_RELOAD,
        affected_components=("hooks", "capture"),
        validator=_min_int(0),
    ),
    SettingDefinition(
        key="codex.hooks.reference_max_bytes",
        category="codex",
        default=1024 * 1024,
        value_type="int",
        description="Maximum bytes fetched from one web reference in Codex Stop hook indexing.",
        env_var="FLUX_KB_CODEX_HOOKS_REFERENCE_MAX_BYTES",
        apply_mode=APPLY_RELOAD,
        affected_components=("hooks", "capture"),
        validator=_min_int(1024),
    ),
    SettingDefinition(
        key="codex.hooks.reference_fetch_timeout_seconds",
        category="codex",
        default=3,
        value_type="int",
        description="Timeout for fetching one web reference in Codex Stop hook indexing.",
        env_var="FLUX_KB_CODEX_HOOKS_REFERENCE_FETCH_TIMEOUT_SECONDS",
        apply_mode=APPLY_RELOAD,
        affected_components=("hooks", "capture"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="codex.hooks.reference_allow_private_urls",
        category="codex",
        default=False,
        value_type="bool",
        description="Allow Codex Stop hook web-reference indexing to fetch private-network URLs.",
        env_var="FLUX_KB_CODEX_HOOKS_REFERENCE_ALLOW_PRIVATE_URLS",
        apply_mode=APPLY_RELOAD,
        affected_components=("hooks", "capture"),
    ),
    SettingDefinition(
        key="codex.hooks.token_budget",
        category="codex",
        default=900,
        value_type="int",
        description="Maximum token budget for Codex hook preflight briefs.",
        env_var="FLUX_KB_CODEX_HOOKS_TOKEN_BUDGET",
        apply_mode=APPLY_RELOAD,
        affected_components=("hooks", "retrieval"),
        validator=_min_int(128),
    ),
    SettingDefinition(
        key="codex.hooks.min_prompt_chars",
        category="codex",
        default=32,
        value_type="int",
        description="Minimum prompt length before Codex preflight retrieval runs.",
        env_var="FLUX_KB_CODEX_HOOKS_MIN_PROMPT_CHARS",
        apply_mode=APPLY_RELOAD,
        affected_components=("hooks",),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="codex.hooks.capture_min_chars",
        category="codex",
        default=160,
        value_type="int",
        description="Minimum final assistant message length before Codex hook capture persists it.",
        env_var="FLUX_KB_CODEX_HOOKS_CAPTURE_MIN_CHARS",
        apply_mode=APPLY_RELOAD,
        affected_components=("hooks", "capture"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="codex.hooks.capture_max_chars",
        category="codex",
        default=8000,
        value_type="int",
        description="Maximum final assistant message characters persisted by Codex hook capture.",
        env_var="FLUX_KB_CODEX_HOOKS_CAPTURE_MAX_CHARS",
        apply_mode=APPLY_RELOAD,
        affected_components=("hooks", "capture"),
        validator=_min_int(256),
    ),
    SettingDefinition(
        key="retrieval.token_budget",
        category="retrieval",
        default=1200,
        value_type="int",
        description="Default context brief token budget.",
        env_var="FLUX_KB_TOKEN_BUDGET",
        affected_components=("retrieval",),
        validator=_min_int(128),
    ),
    SettingDefinition(
        key="retrieval.default_limit",
        category="retrieval",
        default=5,
        value_type="int",
        description="Default result limit for search endpoints.",
        env_var="FLUX_KB_RETRIEVAL_DEFAULT_LIMIT",
        affected_components=("retrieval",),
        validator=_range_int(1, 50),
    ),
    SettingDefinition(
        key="retrieval.search_engine",
        category="retrieval",
        default="vespa",
        value_type="str",
        description="Active retrieval backend used for corpus search.",
        env_var="FLUX_KB_RETRIEVAL_SEARCH_ENGINE",
        apply_mode=APPLY_RELOAD,
        affected_components=("retrieval", "worker"),
        validator=_choice("vespa", "postgres"),
    ),
    SettingDefinition(
        key="retrieval.vespa_base_url",
        category="retrieval",
        default=DEFAULT_VESPA_BASE_URL,
        value_type="str",
        description="Loopback or Docker Compose URL for the local Vespa search sidecar.",
        env_var="FLUX_KB_RETRIEVAL_VESPA_BASE_URL",
        apply_mode=APPLY_RELOAD,
        affected_components=("retrieval", "worker"),
    ),
    SettingDefinition(
        key="retrieval.embedding_model",
        category="retrieval",
        default=SNOWFLAKE_EMBEDDING_MODEL,
        value_type="str",
        description="Dense embedding model used for the active Vespa search index.",
        env_var="FLUX_KB_RETRIEVAL_EMBEDDING_MODEL",
        apply_mode=APPLY_REINDEX_REQUIRED,
        affected_components=("retrieval", "worker", "model-runner"),
    ),
    SettingDefinition(
        key="retrieval.embedding_dimensions",
        category="retrieval",
        default=SNOWFLAKE_EMBEDDING_DIMENSIONS,
        value_type="int",
        description="Dense embedding dimensionality used for the active Vespa search index.",
        env_var="FLUX_KB_RETRIEVAL_EMBEDDING_DIMENSIONS",
        apply_mode=APPLY_REINDEX_REQUIRED,
        affected_components=("retrieval", "worker", "model-runner"),
        validator=_range_int(128, 4096),
    ),
    SettingDefinition(
        key="retrieval.reranker_model",
        category="retrieval",
        default=DEFAULT_RERANKER_MODEL,
        value_type="str",
        description="Final-stage reranker model used after Vespa candidate hydration.",
        env_var="FLUX_KB_RETRIEVAL_RERANKER_MODEL",
        apply_mode=APPLY_RELOAD,
        affected_components=("retrieval", "model-runner"),
    ),
    SettingDefinition(
        key="retrieval.reranker_awq_model",
        category="retrieval",
        default=DEFAULT_RERANKER_AWQ_MODEL,
        value_type="str",
        description="AWQ checkpoint loaded when retrieval.reranker_quantization is awq_int4.",
        env_var="FLUX_KB_RETRIEVAL_RERANKER_AWQ_MODEL",
        apply_mode=APPLY_RELOAD,
        affected_components=("retrieval", "model-runner"),
    ),
    SettingDefinition(
        key="retrieval.reranker_quantization",
        category="retrieval",
        default=DEFAULT_RERANKER_QUANTIZATION,
        value_type="str",
        description="Quantization used for the final reranker: awq_int4, nf4_4bit, or fp16; legacy aliases are canonicalized.",
        env_var="FLUX_KB_RETRIEVAL_RERANKER_QUANTIZATION",
        apply_mode=APPLY_RELOAD,
        affected_components=("retrieval", "model-runner"),
        validator=_reranker_quantization,
    ),
    SettingDefinition(
        key="retrieval.rerank_top_n",
        category="retrieval",
        default=DEFAULT_RERANK_TOP_N,
        value_type="int",
        description="Maximum hydrated candidates sent to the final reranker.",
        env_var="FLUX_KB_RETRIEVAL_RERANK_TOP_N",
        apply_mode=APPLY_RELOAD,
        affected_components=("retrieval", "model-runner"),
        validator=_range_int(1, 200),
    ),
    SettingDefinition(
        key="retrieval.rerank_microbatch_size",
        category="retrieval",
        default=DEFAULT_RERANK_MICROBATCH_SIZE,
        value_type="int",
        description="Passages sent per model-runner rerank request.",
        env_var="FLUX_KB_RETRIEVAL_RERANK_MICROBATCH_SIZE",
        apply_mode=APPLY_RELOAD,
        affected_components=("retrieval",),
        validator=_range_int(1, 32),
    ),
    SettingDefinition(
        key="retrieval.max_rerank_passage_tokens",
        category="retrieval",
        default=DEFAULT_MAX_RERANK_PASSAGE_TOKENS,
        value_type="int",
        description="Maximum passage tokens sent per candidate to the final reranker.",
        env_var="FLUX_KB_RETRIEVAL_MAX_RERANK_PASSAGE_TOKENS",
        apply_mode=APPLY_RELOAD,
        affected_components=("retrieval", "model-runner"),
        validator=_range_int(1, 4096),
    ),
    SettingDefinition(
        key="retrieval.gpu_vram_budget_mb",
        category="retrieval",
        default=10240,
        value_type="int",
        description="Local GPU VRAM budget used to select quantized retrieval model defaults.",
        env_var="FLUX_KB_RETRIEVAL_GPU_VRAM_BUDGET_MB",
        apply_mode=APPLY_RELOAD,
        affected_components=("retrieval", "model-runner"),
        validator=_min_int(1024),
    ),
    SettingDefinition(
        key="gpu.scheduler.enabled",
        category="acceleration",
        default=True,
        value_type="bool",
        description="Enable bounded GPU lease scheduling for local GPU-serving paths.",
        env_var="FLUX_KB_GPU_SCHEDULER_ENABLED",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "paddle-runner", "asr", "worker", "api"),
    ),
    SettingDefinition(
        key="gpu.scheduler.mode",
        category="acceleration",
        default="auto",
        value_type="str",
        description="GPU scheduler coordination backend.",
        env_var="FLUX_KB_GPU_SCHEDULER_MODE",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("model-runner", "paddle-runner", "asr", "worker", "api"),
        validator=_choice("auto", "postgres", "in_process", "disabled"),
    ),
    SettingDefinition(
        key="gpu.scheduler.total_vram_mb",
        category="acceleration",
        default=0,
        value_type="int",
        description="Optional physical GPU VRAM total used for scheduler reporting.",
        env_var="FLUX_KB_GPU_SCHEDULER_TOTAL_VRAM_MB",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "paddle-runner", "asr", "worker", "api"),
        validator=_min_int(0),
    ),
    SettingDefinition(
        key="gpu.scheduler.vram_budget_mb",
        category="acceleration",
        default=10240,
        value_type="int",
        description="Maximum VRAM budget the scheduler may admit after subtracting safety margin.",
        env_var="FLUX_KB_GPU_SCHEDULER_VRAM_BUDGET_MB",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "paddle-runner", "asr", "worker", "api"),
        validator=_min_int(1024),
    ),
    SettingDefinition(
        key="gpu.scheduler.safety_margin_mb",
        category="acceleration",
        default=1024,
        value_type="int",
        description="VRAM kept free when deciding whether to admit GPU work.",
        env_var="FLUX_KB_GPU_SCHEDULER_SAFETY_MARGIN_MB",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "paddle-runner", "asr", "worker", "api"),
        validator=_min_int(0),
    ),
    SettingDefinition(
        key="gpu.scheduler.default_timeout_seconds",
        category="acceleration",
        default=30,
        value_type="int",
        description="Default time a GPU task waits for a lease before returning a retryable busy error.",
        env_var="FLUX_KB_GPU_SCHEDULER_DEFAULT_TIMEOUT_SECONDS",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "paddle-runner", "asr", "worker", "api"),
        validator=_min_int(0),
    ),
    SettingDefinition(
        key="gpu.scheduler.lease_ttl_seconds",
        category="acceleration",
        default=120,
        value_type="int",
        description="Lease expiry window used to recover abandoned GPU work.",
        env_var="FLUX_KB_GPU_SCHEDULER_LEASE_TTL_SECONDS",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "paddle-runner", "asr", "worker", "api"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="gpu.scheduler.heartbeat_interval_seconds",
        category="acceleration",
        default=10,
        value_type="int",
        description="Recommended heartbeat interval for long GPU tasks.",
        env_var="FLUX_KB_GPU_SCHEDULER_HEARTBEAT_INTERVAL_SECONDS",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "paddle-runner", "asr", "worker", "api"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="gpu.scheduler.stale_after_seconds",
        category="acceleration",
        default=180,
        value_type="int",
        description="Age after which stale GPU scheduler records are treated as recoverable.",
        env_var="FLUX_KB_GPU_SCHEDULER_STALE_AFTER_SECONDS",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "paddle-runner", "asr", "worker", "api"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="gpu.scheduler.eviction_enabled",
        category="acceleration",
        default=True,
        value_type="bool",
        description="Allow the GPU scheduler to unload idle resident models before rejecting high-memory work.",
        env_var="FLUX_KB_GPU_SCHEDULER_EVICTION_ENABLED",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "paddle-runner", "asr", "worker", "api"),
    ),
    SettingDefinition(
        key="gpu.scheduler.eviction_request_timeout_seconds",
        category="acceleration",
        default=10,
        value_type="int",
        description="Timeout for scheduler-initiated model unload requests.",
        env_var="FLUX_KB_GPU_SCHEDULER_EVICTION_REQUEST_TIMEOUT_SECONDS",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "paddle-runner", "asr", "worker", "api"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="gpu.scheduler.eviction_max_models",
        category="acceleration",
        default=4,
        value_type="int",
        description="Maximum idle resident models considered during one scheduler eviction pass.",
        env_var="FLUX_KB_GPU_SCHEDULER_EVICTION_MAX_MODELS",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "paddle-runner", "asr", "worker", "api"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="gpu.scheduler.embedding_vram_mb",
        category="acceleration",
        default=2500,
        value_type="int",
        description="Estimated VRAM for the local embedding model profile.",
        env_var="FLUX_KB_GPU_SCHEDULER_EMBEDDING_VRAM_MB",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "worker"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="gpu.scheduler.rerank_vram_mb",
        category="acceleration",
        default=7000,
        value_type="int",
        description="Estimated VRAM for local reranking.",
        env_var="FLUX_KB_GPU_SCHEDULER_RERANK_VRAM_MB",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "worker"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="gpu.scheduler.ocr_image_vram_mb",
        category="acceleration",
        default=2000,
        value_type="int",
        description="Estimated VRAM for ordinary PaddleOCR image OCR.",
        env_var="FLUX_KB_GPU_SCHEDULER_OCR_IMAGE_VRAM_MB",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "paddle-runner", "worker"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="gpu.scheduler.ocr_document_vram_mb",
        category="acceleration",
        default=8000,
        value_type="int",
        description="Estimated VRAM for PaddleOCR-VL document OCR.",
        env_var="FLUX_KB_GPU_SCHEDULER_OCR_DOCUMENT_VRAM_MB",
        apply_mode=APPLY_RELOAD,
        affected_components=("model-runner", "paddle-runner", "worker"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="gpu.scheduler.asr_vram_mb",
        category="acceleration",
        default=6000,
        value_type="int",
        description="Estimated VRAM for local faster-whisper ASR.",
        env_var="FLUX_KB_GPU_SCHEDULER_ASR_VRAM_MB",
        apply_mode=APPLY_RELOAD,
        affected_components=("asr", "worker"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="gpu.scheduler.ollama_vision_vram_mb",
        category="acceleration",
        default=9000,
        value_type="int",
        description="Estimated VRAM for local Ollama vision requests.",
        env_var="FLUX_KB_GPU_SCHEDULER_OLLAMA_VISION_VRAM_MB",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "ollama"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="model_runner.base_url",
        category="acceleration",
        default="http://127.0.0.1:8790",
        value_type="str",
        description="Loopback or Docker Compose URL for the local model-runner service.",
        env_var="FLUX_KB_MODEL_RUNNER_BASE_URL",
        apply_mode=APPLY_RELOAD,
        affected_components=("retrieval", "worker", "model-runner"),
    ),
    SettingDefinition(
        key="model_runner.paddle_runner_base_url",
        category="acceleration",
        default="",
        value_type="str",
        description="Docker Compose URL for the isolated PaddleOCR runner service.",
        env_var="FLUX_KB_PADDLE_RUNNER_BASE_URL",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "model-runner", "paddle-runner", "asr"),
    ),
    SettingDefinition(
        key="ocr.engine",
        category="acceleration",
        default="paddleocr",
        value_type="str",
        description="OCR engine used for images, SVG rasters, and scanned document pages.",
        env_var="FLUX_KB_OCR_ENGINE",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "model-runner"),
        validator=_choice("paddleocr"),
    ),
    SettingDefinition(
        key="ocr.simple_model",
        category="acceleration",
        default="PP-OCRv5",
        value_type="str",
        description="PaddleOCR model family used for ordinary image and SVG OCR.",
        env_var="FLUX_KB_OCR_SIMPLE_MODEL",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "model-runner"),
    ),
    SettingDefinition(
        key="ocr.document_model",
        category="acceleration",
        default="PaddleOCR-VL",
        value_type="str",
        description="PaddleOCR-VL model family used for scanned or complex document pages.",
        env_var="FLUX_KB_OCR_DOCUMENT_MODEL",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "model-runner"),
    ),
    SettingDefinition(
        key="acceleration.cache_root",
        category="acceleration",
        default="",
        value_type="str",
        description="Optional permanent cache root for models, parser output, OCR, ASR, vision, thumbnails, embeddings, and temp artifacts.",
        env_var="FLUX_KB_CACHE_ROOT",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
    ),
    SettingDefinition(
        key="acceleration.asr.enabled",
        category="acceleration",
        default=True,
        value_type="bool",
        description="Enable deferred local ASR for audio and video media jobs when dependencies are available.",
        env_var="FLUX_KB_ASR_ENABLED",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
    ),
    SettingDefinition(
        key="acceleration.asr.provider",
        category="acceleration",
        default="local_faster_whisper",
        value_type="str",
        description="ASR provider used for audio and video media jobs.",
        env_var="FLUX_KB_ASR_PROVIDER",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_choice("local_faster_whisper", "openai_compatible"),
    ),
    SettingDefinition(
        key="acceleration.asr.model",
        category="acceleration",
        default="",
        value_type="str",
        description="ASR model identifier passed to the configured ASR provider.",
        env_var="FLUX_KB_ASR_MODEL",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
    ),
    SettingDefinition(
        key="acceleration.asr.base_url",
        category="acceleration",
        default="",
        value_type="str",
        description="Loopback or Docker Compose URL for the OpenAI-compatible local ASR service.",
        env_var="FLUX_KB_ASR_BASE_URL",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_optional_loopback_http_url,
    ),
    SettingDefinition(
        key="acceleration.asr.model_path",
        category="acceleration",
        default="",
        value_type="str",
        description="Existing local faster-whisper model directory or file path used for ASR without remote model downloads.",
        env_var="FLUX_KB_ASR_MODEL_PATH",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
    ),
    SettingDefinition(
        key="acceleration.asr.max_duration_seconds",
        category="acceleration",
        default=3600,
        value_type="int",
        description="Maximum ASR segment duration for one staged local transcription job.",
        env_var="FLUX_KB_ASR_MAX_DURATION_SECONDS",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="acceleration.asr.device",
        category="acceleration",
        default="auto",
        value_type="str",
        description="faster-whisper execution device for local ASR.",
        env_var="FLUX_KB_ASR_DEVICE",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_choice("auto", "cpu", "cuda"),
    ),
    SettingDefinition(
        key="acceleration.asr.compute_type",
        category="acceleration",
        default="default",
        value_type="str",
        description="faster-whisper compute type for local ASR.",
        env_var="FLUX_KB_ASR_COMPUTE_TYPE",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_choice("default", "float16", "float32", "int8", "int8_float16"),
    ),
    SettingDefinition(
        key="acceleration.vision.enabled",
        category="acceleration",
        default=True,
        value_type="bool",
        description="Enable optional local loopback vision captions for image and sampled video-frame jobs.",
        env_var="FLUX_KB_VISION_ENABLED",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
    ),
    SettingDefinition(
        key="acceleration.vision.model",
        category="acceleration",
        default="qwen3-vl:8b",
        value_type="str",
        description="Local vision model identifier passed to the configured local inference provider.",
        env_var="FLUX_KB_VISION_MODEL",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
    ),
    SettingDefinition(
        key="acceleration.vision.max_image_pixels",
        category="acceleration",
        default=4_096_000,
        value_type="int",
        description="Maximum image pixel count eligible for optional local vision captions.",
        env_var="FLUX_KB_VISION_MAX_IMAGE_PIXELS",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="acceleration.video.frame_sampling.enabled",
        category="acceleration",
        default=True,
        value_type="bool",
        description="Enable bounded transition-aware local frame sampling for video jobs.",
        env_var="FLUX_KB_VIDEO_FRAME_SAMPLING_ENABLED",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
    ),
    SettingDefinition(
        key="acceleration.video.frame_sample_count",
        category="acceleration",
        default=3,
        value_type="int",
        description="Maximum scene-transition frames to sample from one video.",
        env_var="FLUX_KB_VIDEO_FRAME_SAMPLE_COUNT",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_range_int(1, 10),
    ),
    SettingDefinition(
        key="acceleration.video.scene_threshold",
        category="acceleration",
        default=0.35,
        value_type="float",
        description="ffmpeg scene-change threshold used for transition-aware video frame sampling.",
        env_var="FLUX_KB_VIDEO_SCENE_THRESHOLD",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_range_float(0.0, 1.0),
    ),
    SettingDefinition(
        key="acceleration.video.frame_max_duration_seconds",
        category="acceleration",
        default=1800,
        value_type="int",
        description="Legacy frame-sampling duration hint retained for compatibility; staged video jobs use bounded frame timestamp sets instead of skipping long videos.",
        env_var="FLUX_KB_VIDEO_FRAME_MAX_DURATION_SECONDS",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="acceleration.local_inference.enabled",
        category="acceleration",
        default=True,
        value_type="bool",
        description="Enable local loopback or Docker host-gateway probing for optional local model servers.",
        env_var="FLUX_KB_LOCAL_INFERENCE_ENABLED",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
    ),
    SettingDefinition(
        key="acceleration.local_inference.provider",
        category="acceleration",
        default="ollama",
        value_type="str",
        description="Local model server provider identifier.",
        env_var="FLUX_KB_LOCAL_INFERENCE_PROVIDER",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_choice("ollama", "llama_cpp", "openai_compatible"),
    ),
    SettingDefinition(
        key="acceleration.local_inference.base_url",
        category="acceleration",
        default="http://127.0.0.1:11434",
        value_type="str",
        description="Local model server base URL using loopback or Docker host gateway.",
        env_var="FLUX_KB_LOCAL_INFERENCE_BASE_URL",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_loopback_http_url,
    ),
    SettingDefinition(
        key="acceleration.local_inference.keep_alive",
        category="acceleration",
        default="2m",
        value_type="str",
        description="Optional local model residency duration sent to providers that support per-request keepalive.",
        env_var="FLUX_KB_LOCAL_INFERENCE_KEEP_ALIVE",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
    ),
    SettingDefinition(
        key="acceleration.local_inference.probe_timeout_seconds",
        category="acceleration",
        default=1,
        value_type="int",
        description="Timeout for optional localhost model-server capability probes.",
        env_var="FLUX_KB_LOCAL_INFERENCE_PROBE_TIMEOUT_SECONDS",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="governance.librarian.enabled",
        category="governance",
        default=False,
        value_type="bool",
        description="Enable the background memory governance librarian loop; defaults off.",
        env_var="FLUX_KB_GOVERNANCE_LIBRARIAN_ENABLED",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
    ),
    SettingDefinition(
        key="governance.librarian.interval_seconds",
        category="governance",
        default=3600,
        value_type="int",
        description="Minimum seconds between background governance librarian runs.",
        env_var="FLUX_KB_GOVERNANCE_LIBRARIAN_INTERVAL_SECONDS",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("worker",),
        validator=_min_int(60),
    ),
    SettingDefinition(
        key="governance.librarian.mode",
        category="governance",
        default="shadow",
        value_type="str",
        description="Governance librarian mode: shadow, manual, or auto.",
        env_var="FLUX_KB_GOVERNANCE_LIBRARIAN_MODE",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
        validator=_choice("shadow", "manual", "auto"),
    ),
    SettingDefinition(
        key="governance.librarian.max_actions_per_run",
        category="governance",
        default=25,
        value_type="int",
        description="Maximum governance proposals generated in one run.",
        env_var="FLUX_KB_GOVERNANCE_MAX_ACTIONS_PER_RUN",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
        validator=_range_int(1, 200),
    ),
    SettingDefinition(
        key="governance.librarian.min_shadow_precision",
        category="governance",
        default=0.8,
        value_type="float",
        description="Minimum governance-shadow proposal precision required before apply is allowed.",
        env_var="FLUX_KB_GOVERNANCE_MIN_SHADOW_PRECISION",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
        validator=_range_float(0.0, 1.0),
    ),
    SettingDefinition(
        key="governance.librarian.auto_apply_enabled",
        category="governance",
        default=False,
        value_type="bool",
        description="Enable guarded low-risk governance auto-apply; defaults off.",
        env_var="FLUX_KB_GOVERNANCE_AUTO_APPLY_ENABLED",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("worker",),
    ),
    SettingDefinition(
        key="governance.librarian.auto_apply_risk_ceiling",
        category="governance",
        default="low",
        value_type="str",
        description="Highest governance risk class eligible for auto-apply.",
        env_var="FLUX_KB_GOVERNANCE_AUTO_APPLY_RISK_CEILING",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("worker",),
        validator=_choice("low", "medium", "high"),
    ),
    SettingDefinition(
        key="governance.librarian.digest_retention_days",
        category="governance",
        default=30,
        value_type="int",
        description="Retention window for local governance digest read models.",
        env_var="FLUX_KB_GOVERNANCE_DIGEST_RETENTION_DAYS",
        apply_mode=APPLY_RELOAD,
        affected_components=("api", "cli", "mcp", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="governance.librarian.protected_memory_rules",
        category="governance",
        default='{"protect_metadata_flag":true,"protect_confirmed_confidence":0.85,"protect_reinforced_confidence":0.75,"protect_active_capture_review":true}',
        value_type="str",
        description="JSON object describing rule-based protected-memory policy thresholds.",
        env_var="FLUX_KB_GOVERNANCE_PROTECTED_MEMORY_RULES",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
    ),
    SettingDefinition(
        key="governance.local_model_rationale.enabled",
        category="governance",
        default=False,
        value_type="bool",
        description="Enable optional local-only model rationale drafts for governance proposals.",
        env_var="FLUX_KB_GOVERNANCE_LOCAL_MODEL_RATIONALE_ENABLED",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
    ),
    SettingDefinition(
        key="governance.local_model_rationale.model",
        category="governance",
        default="",
        value_type="str",
        description="Local model identifier for optional governance rationale drafts.",
        env_var="FLUX_KB_GOVERNANCE_LOCAL_MODEL_RATIONALE_MODEL",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
    ),
    SettingDefinition(
        key="operator.automation.enabled",
        category="operator",
        default=False,
        value_type="bool",
        description="Enable guarded dashboard automation passes; defaults off.",
        env_var="FLUX_KB_OPERATOR_AUTOMATION_ENABLED",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
    ),
    SettingDefinition(
        key="operator.automation.mode",
        category="operator",
        default="guarded",
        value_type="str",
        description="Operator automation posture: guarded executes allowlisted safe actions, suggest_only records proposals only.",
        env_var="FLUX_KB_OPERATOR_AUTOMATION_MODE",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
        validator=_choice("guarded", "suggest_only"),
    ),
    SettingDefinition(
        key="operator.automation.interval_seconds",
        category="operator",
        default=1800,
        value_type="int",
        description="Minimum seconds between background guarded automation passes.",
        env_var="FLUX_KB_OPERATOR_AUTOMATION_INTERVAL_SECONDS",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("worker",),
        validator=_min_int(60),
    ),
    SettingDefinition(
        key="operator.automation.evidence_freshness_hours",
        category="operator",
        default=336,
        value_type="int",
        description="Evidence age window used when deciding whether safe evidence refreshes are eligible.",
        env_var="FLUX_KB_OPERATOR_AUTOMATION_EVIDENCE_FRESHNESS_HOURS",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="operator.automation.max_actions_per_run",
        category="operator",
        default=25,
        value_type="int",
        description="Maximum allowlisted automation actions evaluated in one guarded pass.",
        env_var="FLUX_KB_OPERATOR_AUTOMATION_MAX_ACTIONS_PER_RUN",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
        validator=_range_int(1, 200),
    ),
    SettingDefinition(
        key="operator.automation.auto_refresh_evidence",
        category="operator",
        default=True,
        value_type="bool",
        description="Allow guarded automation to refresh retrieval and reliability evidence.",
        env_var="FLUX_KB_OPERATOR_AUTOMATION_REFRESH_EVIDENCE",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
    ),
    SettingDefinition(
        key="operator.automation.auto_ingest_approved_capture",
        category="operator",
        default=True,
        value_type="bool",
        description="Allow guarded automation to ingest captures that were already manually approved.",
        env_var="FLUX_KB_OPERATOR_AUTOMATION_INGEST_APPROVED_CAPTURE",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
    ),
    SettingDefinition(
        key="operator.automation.auto_remediate_diagnostics",
        category="operator",
        default=True,
        value_type="bool",
        description="Allow guarded automation to run non-destructive diagnostic recovery actions.",
        env_var="FLUX_KB_OPERATOR_AUTOMATION_REMEDIATE_DIAGNOSTICS",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
    ),
    SettingDefinition(
        key="operator.automation.auto_sync_search_index",
        category="operator",
        default=True,
        value_type="bool",
        description="Allow guarded automation to enqueue stale or missing Vespa search-index sync work.",
        env_var="FLUX_KB_OPERATOR_AUTOMATION_SYNC_SEARCH_INDEX",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
    ),
    SettingDefinition(
        key="operator.automation.auto_run_governance_shadow",
        category="operator",
        default=True,
        value_type="bool",
        description="Allow guarded automation to run governance in shadow/proposal mode only.",
        env_var="FLUX_KB_OPERATOR_AUTOMATION_GOVERNANCE_SHADOW",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "api", "cli", "mcp", "dashboard"),
    ),
    SettingDefinition(
        key="privacy.redactions.enabled",
        category="privacy",
        default=False,
        value_type="bool",
        description="Enable masking of secret-like text, local paths, and diagnostic values before persistence or display.",
        env_var="FLUX_KB_REDACTIONS_ENABLED",
        apply_mode=APPLY_RELOAD,
        affected_components=("api", "cli", "mcp", "worker", "hooks", "dashboard"),
    ),
    SettingDefinition(
        key="acceleration.worker_cap.text",
        category="acceleration",
        default=8,
        value_type="int",
        description="Maximum text-family extraction workers.",
        env_var="FLUX_KB_WORKER_CAP_TEXT",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="acceleration.worker_cap.office",
        category="acceleration",
        default=3,
        value_type="int",
        description="Maximum Office/PDF-family extraction workers.",
        env_var="FLUX_KB_WORKER_CAP_OFFICE",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="acceleration.worker_cap.image",
        category="acceleration",
        default=2,
        value_type="int",
        description="Maximum image-family extraction workers.",
        env_var="FLUX_KB_WORKER_CAP_IMAGE",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="acceleration.worker_cap.diagram",
        category="acceleration",
        default=2,
        value_type="int",
        description="Maximum diagram-family extraction workers.",
        env_var="FLUX_KB_WORKER_CAP_DIAGRAM",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="acceleration.worker_cap.archive",
        category="acceleration",
        default=3,
        value_type="int",
        description="Maximum archive/container-family extraction workers.",
        env_var="FLUX_KB_WORKER_CAP_ARCHIVE",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="acceleration.worker_cap.media",
        category="acceleration",
        default=2,
        value_type="int",
        description="Maximum media-family extraction workers.",
        env_var="FLUX_KB_WORKER_CAP_MEDIA",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="acceleration.worker_cap.embedding",
        category="acceleration",
        default=2,
        value_type="int",
        description="Maximum embedding-family workers.",
        env_var="FLUX_KB_WORKER_CAP_EMBEDDING",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="acceleration.worker_cap.preview",
        category="acceleration",
        default=2,
        value_type="int",
        description="Maximum preview-generation workers.",
        env_var="FLUX_KB_WORKER_CAP_PREVIEW",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="acceleration.worker_cap.general",
        category="acceleration",
        default=4,
        value_type="int",
        description="Maximum general fallback workers.",
        env_var="FLUX_KB_WORKER_CAP_GENERAL",
        apply_mode=APPLY_RELOAD,
        affected_components=("worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="crawler.max_inline_bytes",
        category="crawler",
        default=256 * 1024,
        value_type="int",
        description="Default maximum file size for inline text extraction.",
        env_var="FLUX_KB_CRAWLER_MAX_INLINE_BYTES",
        affected_components=("crawler",),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="crawler.heavy_threshold_bytes",
        category="crawler",
        default=10 * 1024 * 1024,
        value_type="int",
        description="Default size above which files are deferred to background jobs.",
        env_var="FLUX_KB_CRAWLER_HEAVY_THRESHOLD_BYTES",
        affected_components=("crawler", "worker"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="crawler.container_max_depth",
        category="crawler",
        default=2,
        value_type="int",
        description="Maximum archive/container nesting depth eligible for local recursive extraction.",
        env_var="FLUX_KB_CRAWLER_CONTAINER_MAX_DEPTH",
        apply_mode=APPLY_RELOAD,
        affected_components=("crawler", "worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="crawler.container_max_members",
        category="crawler",
        default=200,
        value_type="int",
        description="Maximum archive/container members to enumerate during local extraction.",
        env_var="FLUX_KB_CRAWLER_CONTAINER_MAX_MEMBERS",
        apply_mode=APPLY_RELOAD,
        affected_components=("crawler", "worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="crawler.container_max_total_bytes",
        category="crawler",
        default=50 * 1024 * 1024,
        value_type="int",
        description="Maximum total uncompressed bytes to read from one archive/container.",
        env_var="FLUX_KB_CRAWLER_CONTAINER_MAX_TOTAL_BYTES",
        apply_mode=APPLY_RELOAD,
        affected_components=("crawler", "worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="crawler.container_max_member_bytes",
        category="crawler",
        default=10 * 1024 * 1024,
        value_type="int",
        description="Maximum uncompressed size for a single archive/container member.",
        env_var="FLUX_KB_CRAWLER_CONTAINER_MAX_MEMBER_BYTES",
        apply_mode=APPLY_RELOAD,
        affected_components=("crawler", "worker", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="crawler.hash_parallelism",
        category="crawler",
        default=8,
        value_type="int",
        description="Maximum bounded hashing concurrency for crawl/reconcile scans.",
        env_var="FLUX_KB_CRAWLER_HASH_PARALLELISM",
        apply_mode=APPLY_RELOAD,
        affected_components=("crawler", "watcher"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="crawler.global_include_globs",
        category="crawler",
        default=[],
        value_type="list[str]",
        description="Global include glob defaults inherited by monitored roots unless overridden.",
        env_var="FLUX_KB_CRAWLER_GLOBAL_INCLUDE_GLOBS",
        apply_mode=APPLY_RELOAD,
        affected_components=("crawler", "watcher", "dashboard"),
    ),
    SettingDefinition(
        key="crawler.global_exclude_globs",
        category="crawler",
        default=DEFAULT_CRAWLER_GLOBAL_EXCLUDE_GLOBS,
        value_type="list[str]",
        description="Global exclude glob defaults inherited by monitored roots unless overridden.",
        env_var="FLUX_KB_CRAWLER_GLOBAL_EXCLUDE_GLOBS",
        apply_mode=APPLY_RELOAD,
        affected_components=("crawler", "watcher", "dashboard"),
    ),
    SettingDefinition(
        key="crawler.unseen_asset_purge_grace_seconds",
        category="crawler",
        default=86400,
        value_type="int",
        description="Grace period before unseen corpus assets are physically purged from index tables.",
        env_var="FLUX_KB_UNSEEN_ASSET_PURGE_GRACE_SECONDS",
        apply_mode=APPLY_RELOAD,
        affected_components=("crawler", "worker", "dashboard"),
        validator=_min_int(0),
    ),
    SettingDefinition(
        key="crawler.unseen_asset_purge_batch_size",
        category="crawler",
        default=500,
        value_type="int",
        description="Maximum unseen corpus assets to physically purge per worker cleanup pass.",
        env_var="FLUX_KB_UNSEEN_ASSET_PURGE_BATCH_SIZE",
        apply_mode=APPLY_RELOAD,
        affected_components=("crawler", "worker", "dashboard"),
        validator=_range_int(1, 5000),
    ),
    SettingDefinition(
        key="watcher.backend",
        category="watcher",
        default="auto",
        value_type="str",
        description="Filesystem watcher backend policy: auto, watchdog, or polling.",
        env_var="FLUX_KB_WATCHER_BACKEND",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("watcher", "host-agent", "dashboard"),
        validator=_choice("auto", "watchdog", "polling"),
    ),
    SettingDefinition(
        key="watcher.interval_seconds",
        category="watcher",
        default=2.0,
        value_type="float",
        description="Filesystem watcher polling/reload interval.",
        env_var="FLUX_KB_WATCHER_INTERVAL_SECONDS",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("watcher",),
    ),
    SettingDefinition(
        key="watcher.debounce_seconds",
        category="watcher",
        default=2.0,
        value_type="float",
        description="Debounce window for repeated filesystem events.",
        env_var="FLUX_KB_WATCHER_DEBOUNCE_SECONDS",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("watcher",),
    ),
    SettingDefinition(
        key="watcher.stability_quiet_seconds",
        category="watcher",
        default=2.0,
        value_type="float",
        description="Minimum unchanged size/mtime quiet window before watcher-triggered indexing.",
        env_var="FLUX_KB_WATCHER_STABILITY_QUIET_SECONDS",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("watcher", "host-agent"),
    ),
    SettingDefinition(
        key="watcher.large_file_stability_quiet_seconds",
        category="watcher",
        default=30.0,
        value_type="float",
        description="Longer stability window reserved for large or cloud-synced files.",
        env_var="FLUX_KB_WATCHER_LARGE_FILE_STABILITY_QUIET_SECONDS",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("watcher", "host-agent"),
    ),
    SettingDefinition(
        key="watcher.max_queue_size",
        category="watcher",
        default=1000,
        value_type="int",
        description="Maximum pending watcher events before suppression.",
        env_var="FLUX_KB_WATCHER_MAX_QUEUE_SIZE",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("watcher",),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="watcher.stale_after_seconds",
        category="watcher",
        default=120,
        value_type="int",
        description="Heartbeat age after which a watcher is marked stale.",
        env_var="FLUX_KB_WATCHER_STALE_AFTER_SECONDS",
        affected_components=("dashboard", "watcher"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="watcher.reconcile_on_start",
        category="watcher",
        default=True,
        value_type="bool",
        description="Run a full watched-root reconciliation when watcher services start.",
        env_var="FLUX_KB_WATCHER_RECONCILE_ON_START",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("watcher", "host-agent"),
    ),
    SettingDefinition(
        key="watcher.reconcile_interval_seconds",
        category="watcher",
        default=3600,
        value_type="int",
        description="Periodic full reconciliation interval for enabled watched roots.",
        env_var="FLUX_KB_WATCHER_RECONCILE_INTERVAL_SECONDS",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("watcher", "host-agent"),
        validator=_min_int(60),
    ),
    SettingDefinition(
        key="worker.batch_size",
        category="worker",
        default=24,
        value_type="int",
        description="Default corpus/mail job batch size.",
        env_var="FLUX_KB_WORKER_BATCH_SIZE",
        affected_components=("worker",),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="worker.default_workers",
        category="worker",
        default=8,
        value_type="int",
        description="Default corpus job processing threads when a worker command omits --workers.",
        env_var="FLUX_KB_WORKER_DEFAULT_WORKERS",
        affected_components=("worker", "host-agent", "dashboard"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="worker.retry_cooldown_seconds",
        category="worker",
        default=300,
        value_type="int",
        description="Default retry cooldown for failed background jobs.",
        env_var="FLUX_KB_WORKER_RETRY_COOLDOWN_SECONDS",
        affected_components=("worker",),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="worker.failure_max_attempts",
        category="worker",
        default=3,
        value_type="int",
        description="Number of non-lock worker failures before marking a corpus job failed.",
        env_var="FLUX_KB_WORKER_FAILURE_MAX_ATTEMPTS",
        affected_components=("worker", "host-agent"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="worker.lock_retry_cooldown_seconds",
        category="worker",
        default=300,
        value_type="int",
        description="Retry cooldown for locked corpus files before another extraction attempt.",
        env_var="FLUX_KB_WORKER_LOCK_RETRY_COOLDOWN_SECONDS",
        affected_components=("worker", "host-agent"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="worker.lock_max_attempts",
        category="worker",
        default=3,
        value_type="int",
        description="Number of locked-file attempts before marking a corpus job blocked_locked.",
        env_var="FLUX_KB_WORKER_LOCK_MAX_ATTEMPTS",
        affected_components=("worker", "host-agent"),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="host_agent.vss_enabled",
        category="host_agent",
        default=True,
        value_type="bool",
        description="Enable Windows Volume Shadow Copy fallback for locked host-agent local files.",
        env_var="FLUX_KB_HOST_AGENT_VSS_ENABLED",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("host-agent",),
    ),
    SettingDefinition(
        key="host_agent.vss_max_file_bytes",
        category="host_agent",
        default=512 * 1024 * 1024,
        value_type="int",
        description="Maximum file size eligible for VSS fallback attempts.",
        env_var="FLUX_KB_HOST_AGENT_VSS_MAX_FILE_BYTES",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("host-agent",),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="host_agent.vss_timeout_seconds",
        category="host_agent",
        default=30,
        value_type="int",
        description="Maximum time budget for VSS create/delete operations.",
        env_var="FLUX_KB_HOST_AGENT_VSS_TIMEOUT_SECONDS",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("host-agent",),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="dashboard.poll_interval_seconds",
        category="dashboard",
        default=10,
        value_type="int",
        description="Dashboard JSON refresh interval.",
        env_var="FLUX_KB_DASHBOARD_POLL_INTERVAL_SECONDS",
        affected_components=("dashboard",),
        validator=_min_int(1),
    ),
    SettingDefinition(
        key="mail.imap.poll_interval_seconds",
        category="mail",
        default=60,
        value_type="int",
        description="IMAP reconciliation interval for monitored folders.",
        env_var="FLUX_KB_MAIL_IMAP_POLL_INTERVAL_SECONDS",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("mail",),
        validator=_min_int(5),
    ),
    SettingDefinition(
        key="mail.imap.use_idle",
        category="mail",
        default=True,
        value_type="bool",
        description="Prefer IMAP IDLE when available, with polling reconciliation.",
        env_var="FLUX_KB_MAIL_IMAP_USE_IDLE",
        apply_mode=APPLY_RESTART_COMPONENT,
        affected_components=("mail",),
    ),
    SettingDefinition(
        key="mail.imap.oauth_refresh_token",
        category="mail",
        default="",
        value_type="str",
        description="Legacy manual IMAP XOAUTH2 token override. Prefer profile OAuth setup.",
        env_var="FLUX_KB_MAIL_IMAP_OAUTH_REFRESH_TOKEN",
        sensitive=True,
        apply_mode=APPLY_RELOAD,
        affected_components=("mail",),
    ),
    SettingDefinition(
        key="mail.oauth.google.client_config_path",
        category="mail",
        default="",
        value_type="str",
        description="Optional default private Google OAuth desktop client JSON path.",
        env_var="FLUX_KB_MAIL_GOOGLE_CLIENT_CONFIG_PATH",
        sensitive=True,
        affected_components=("mail", "dashboard"),
    ),
    SettingDefinition(
        key="mail.oauth.google.redirect_uri",
        category="mail",
        default="http://127.0.0.1:8765",
        value_type="str",
        description="Loopback redirect URI for Gmail installed-app OAuth.",
        env_var="FLUX_KB_MAIL_GOOGLE_REDIRECT_URI",
        apply_mode=APPLY_RELOAD,
        affected_components=("mail", "dashboard"),
    ),
    SettingDefinition(
        key="mail.oauth.google.scope",
        category="mail",
        default="https://mail.google.com/",
        value_type="str",
        description="Gmail IMAP XOAUTH2 scope.",
        env_var="FLUX_KB_MAIL_GOOGLE_SCOPE",
        read_only=True,
        affected_components=("mail",),
    ),
    SettingDefinition(
        key="mail.post_process.default_policy",
        category="mail",
        default="move_to_processed",
        value_type="str",
        description="Default action after successful mail export.",
        env_var="FLUX_KB_MAIL_POST_PROCESS_DEFAULT_POLICY",
        apply_mode=APPLY_RELOAD,
        affected_components=("mail",),
        validator=_choice("none", "move_to_processed", "remove_label", "trash"),
    ),
)

_REGISTRY_BY_KEY = {definition.key: definition for definition in SETTING_REGISTRY}
