<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../FluxKnowledge.Application/FluxKnowledge.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="Syncfusion.Pdf.Net.Core" />
    <PackageReference Include="Syncfusion.PdfToImageConverter.Net.Core" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Web.Administration">
      <HintPath>$(windir)\System32\inetsrv\Microsoft.Web.Administration.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="Documents\paddleocr_vl_executor.py">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
