[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$SourcePath,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$SourcePath = (Resolve-Path -LiteralPath $SourcePath).Path
$OutputPath = [System.IO.Path]::GetFullPath($OutputPath)
$source = [System.IO.File]::ReadAllText($SourcePath).Replace("`r`n", "`n").Replace("`r", "`n")
if (-not $source.StartsWith(":On Error exit`n", [StringComparison]::Ordinal)) {
    throw 'The bootstrap source must terminate SQLCMD on the first failed batch.'
}
if ($source -match '(?i)(CERTIFICATE|ADD\s+SIGNATURE|DROP\s+SIGNATURE|CRYPT_PROPERTIES)') {
    throw 'The direct-admin bootstrap source contains removed signing machinery.'
}
$procedureNames = @(
    'FluxKnowledgeNativeGoLiveCreate'
    'FluxKnowledgeNativeGoLiveDrop'
    'FluxKnowledgeNativeGoLiveManageAppPool'
    'FluxKnowledgeNativeGoLiveObserveAppPool'
)
$firstProcedure = $source.IndexOf('-- BEGIN HASHED PROCEDURE:', [StringComparison]::Ordinal)
$existingProcedureGuard = [regex]::Match(
    $source,
    "(?s)IF EXISTS \(.*?sys\.procedures.*?FluxKnowledgeNativeGoLiveCreate.*?FluxKnowledgeNativeGoLiveDrop.*?FluxKnowledgeNativeGoLiveManageAppPool.*?FluxKnowledgeNativeGoLiveObserveAppPool.*?\)\s*THROW 51000, 'native-go-live-bootstrap-procedure-already-exists', 1;")
if (-not $existingProcedureGuard.Success -or $existingProcedureGuard.Index -ge $firstProcedure) {
    throw 'The bootstrap source does not refuse existing canonical procedure objects before definition.'
}
if ($source -notmatch 'ALTER\s+SERVER\s+ROLE\s+\[sysadmin\]\s+ADD\s+MEMBER\s+\[IIS AppPool\\FluxKnowledge\]') {
    throw 'The bootstrap source does not grant the fixed app-pool login sysadmin membership.'
}

function Get-Sha256 {
    param([byte[]]$Bytes)
    $sha256 = [System.Security.Cryptography.SHA256]::Create()
    try {
        return [Convert]::ToHexString($sha256.ComputeHash($Bytes)).ToLowerInvariant()
    }
    finally {
        $sha256.Dispose()
    }
}

$definitionHashes = [ordered]@{}
$sourceHash = Get-Sha256 ([System.Text.Encoding]::UTF8.GetBytes($source))
foreach ($name in $procedureNames) {
    $start = "-- BEGIN HASHED PROCEDURE: $name`n"
    $end = "GO`n-- END HASHED PROCEDURE: $name"
    $startIndex = $source.IndexOf($start, [StringComparison]::Ordinal)
    if ($startIndex -lt 0) { throw "Missing bootstrap procedure start marker: $name" }
    $definitionStart = $startIndex + $start.Length
    $endIndex = $source.IndexOf($end, $definitionStart, [StringComparison]::Ordinal)
    if ($endIndex -lt 0) { throw "Missing bootstrap procedure end marker: $name" }
    $definition = $source.Substring($definitionStart, $endIndex - $definitionStart)
    if (-not $definition.StartsWith("CREATE PROCEDURE dbo.$name`n", [StringComparison]::Ordinal)) {
        throw "The hashed definition is not the expected creation-only canonical procedure: $name"
    }
    if ($definition -match '(?m)^GO\s*$') { throw "A nested batch separator exists in $name" }
    $definitionHashes[$name] = Get-Sha256 ([System.Text.Encoding]::Unicode.GetBytes($definition))
}

$manifestInput = "native-go-live-bootstrap-manifest-v3`nsource:$sourceHash`n"
foreach ($name in $procedureNames) {
    $manifestInput += "${name}:$($definitionHashes[$name])`n"
}
$manifestHash = Get-Sha256 ([System.Text.Encoding]::UTF8.GetBytes($manifestInput))

$generated = @"
// <auto-generated />
namespace FluxKnowledge.Integrations.Windows.NativeGoLive;

internal static partial class NativeGoLiveSqlBootstrapAuthorityContract
{
    internal const string BootstrapSourceSha256 = "$sourceHash";
    internal const string ProcedureManifestSha256 = "$manifestHash";

    internal static string DefinitionSha256(string procedureName) => procedureName switch
    {
        "FluxKnowledgeNativeGoLiveCreate" => "$($definitionHashes['FluxKnowledgeNativeGoLiveCreate'])",
        "FluxKnowledgeNativeGoLiveDrop" => "$($definitionHashes['FluxKnowledgeNativeGoLiveDrop'])",
        "FluxKnowledgeNativeGoLiveManageAppPool" => "$($definitionHashes['FluxKnowledgeNativeGoLiveManageAppPool'])",
        "FluxKnowledgeNativeGoLiveObserveAppPool" => "$($definitionHashes['FluxKnowledgeNativeGoLiveObserveAppPool'])",
        _ => throw new ArgumentOutOfRangeException(nameof(procedureName))
    };
}
"@.Replace("`r`n", "`n").Replace("`r", "`n")

$outputDirectory = [System.IO.Path]::GetDirectoryName($OutputPath)
if (-not [string]::IsNullOrEmpty($outputDirectory)) {
    [System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
}
[System.IO.File]::WriteAllText($OutputPath, $generated, [System.Text.UTF8Encoding]::new($false))
